// This file was auto-generated by Fern from our API Definition.

import { AssetsClient } from "./api/resources/assets/client/Client.js";
import { AssignmentsClient } from "./api/resources/assignments/client/Client.js";
import { IdentityClient } from "./api/resources/identity/client/Client.js";
import { InvitesClient } from "./api/resources/invites/client/Client.js";
import { LookupsClient } from "./api/resources/lookups/client/Client.js";
import { OperatorsClient } from "./api/resources/operators/client/Client.js";
import { OrganizationsClient } from "./api/resources/organizations/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "./BaseClient.js";
import * as core from "./core/index.js";

export declare namespace NizamDashboardClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class NizamDashboardClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<NizamDashboardClient.Options>;
    protected _assets: AssetsClient | undefined;
    protected _assignments: AssignmentsClient | undefined;
    protected _invites: InvitesClient | undefined;
    protected _lookups: LookupsClient | undefined;
    protected _identity: IdentityClient | undefined;
    protected _organizations: OrganizationsClient | undefined;
    protected _operators: OperatorsClient | undefined;

    constructor(options: NizamDashboardClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get assets(): AssetsClient {
        return (this._assets ??= new AssetsClient(this._options));
    }

    public get assignments(): AssignmentsClient {
        return (this._assignments ??= new AssignmentsClient(this._options));
    }

    public get invites(): InvitesClient {
        return (this._invites ??= new InvitesClient(this._options));
    }

    public get lookups(): LookupsClient {
        return (this._lookups ??= new LookupsClient(this._options));
    }

    public get identity(): IdentityClient {
        return (this._identity ??= new IdentityClient(this._options));
    }

    public get organizations(): OrganizationsClient {
        return (this._organizations ??= new OrganizationsClient(this._options));
    }

    public get operators(): OperatorsClient {
        return (this._operators ??= new OperatorsClient(this._options));
    }

    /**
     * Make a passthrough request using the SDK's configured auth, retry, logging, etc.
     * This is useful for making requests to endpoints not yet supported in the SDK.
     * The input can be a URL string, URL object, or Request object. Relative paths are resolved against the configured base URL.
     *
     * @param {Request | string | URL} input - The URL, path, or Request object.
     * @param {RequestInit} init - Standard fetch RequestInit options.
     * @param {core.PassthroughRequest.RequestOptions} requestOptions - Per-request overrides (timeout, retries, headers, abort signal).
     * @returns {Promise<Response>} A standard Response object.
     */
    public async fetch(
        input: Request | string | URL,
        init?: RequestInit,
        requestOptions?: core.PassthroughRequest.RequestOptions,
    ): Promise<Response> {
        return core.makePassthroughRequest(
            input,
            init,
            {
                baseUrl: this._options.baseUrl ?? this._options.environment,
                headers: this._options.headers,
                timeoutInSeconds: this._options.timeoutInSeconds,
                maxRetries: this._options.maxRetries,
                fetch: this._options.fetch,
                logging: this._options.logging,
                getAuthHeaders: async () => (await this._options.authProvider.getAuthRequest()).headers,
            },
            requestOptions,
        );
    }
}
