// This file was auto-generated by Fern from our API Definition.

import { ActiveOrganizationClient } from "./api/resources/activeOrganization/client/Client.js";
import { ActivityClient } from "./api/resources/activity/client/Client.js";
import { AssetsClient } from "./api/resources/assets/client/Client.js";
import { AssignmentsClient } from "./api/resources/assignments/client/Client.js";
import { DevicesClient } from "./api/resources/devices/client/Client.js";
import { FilesClient } from "./api/resources/files/client/Client.js";
import { ImportsClient } from "./api/resources/imports/client/Client.js";
import { InvitesClient } from "./api/resources/invites/client/Client.js";
import { JobsClient } from "./api/resources/jobs/client/Client.js";
import { LookupsClient } from "./api/resources/lookups/client/Client.js";
import { MembershipsClient } from "./api/resources/memberships/client/Client.js";
import { NotificationPreferencesClient } from "./api/resources/notificationPreferences/client/Client.js";
import { NotificationsClient } from "./api/resources/notifications/client/Client.js";
import { OperatorsClient } from "./api/resources/operators/client/Client.js";
import { OrganizationsClient } from "./api/resources/organizations/client/Client.js";
import { PositionsClient } from "./api/resources/positions/client/Client.js";
import { RealtimeClient } from "./api/resources/realtime/client/Client.js";
import { TaskAttemptsClient } from "./api/resources/taskAttempts/client/Client.js";
import { TasksClient } from "./api/resources/tasks/client/Client.js";
import { UsersClient } from "./api/resources/users/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "./BaseClient.js";
import * as core from "./core/index.js";

export declare namespace NizamDashboardClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class NizamDashboardClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<NizamDashboardClient.Options>;
    protected _activity: ActivityClient | undefined;
    protected _assets: AssetsClient | undefined;
    protected _assignments: AssignmentsClient | undefined;
    protected _files: FilesClient | undefined;
    protected _positions: PositionsClient | undefined;
    protected _imports: ImportsClient | undefined;
    protected _invites: InvitesClient | undefined;
    protected _jobs: JobsClient | undefined;
    protected _lookups: LookupsClient | undefined;
    protected _users: UsersClient | undefined;
    protected _activeOrganization: ActiveOrganizationClient | undefined;
    protected _devices: DevicesClient | undefined;
    protected _memberships: MembershipsClient | undefined;
    protected _notificationPreferences: NotificationPreferencesClient | undefined;
    protected _notifications: NotificationsClient | undefined;
    protected _operators: OperatorsClient | undefined;
    protected _organizations: OrganizationsClient | undefined;
    protected _realtime: RealtimeClient | undefined;
    protected _taskAttempts: TaskAttemptsClient | undefined;
    protected _tasks: TasksClient | undefined;

    constructor(options: NizamDashboardClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get activity(): ActivityClient {
        return (this._activity ??= new ActivityClient(this._options));
    }

    public get assets(): AssetsClient {
        return (this._assets ??= new AssetsClient(this._options));
    }

    public get assignments(): AssignmentsClient {
        return (this._assignments ??= new AssignmentsClient(this._options));
    }

    public get files(): FilesClient {
        return (this._files ??= new FilesClient(this._options));
    }

    public get positions(): PositionsClient {
        return (this._positions ??= new PositionsClient(this._options));
    }

    public get imports(): ImportsClient {
        return (this._imports ??= new ImportsClient(this._options));
    }

    public get invites(): InvitesClient {
        return (this._invites ??= new InvitesClient(this._options));
    }

    public get jobs(): JobsClient {
        return (this._jobs ??= new JobsClient(this._options));
    }

    public get lookups(): LookupsClient {
        return (this._lookups ??= new LookupsClient(this._options));
    }

    public get users(): UsersClient {
        return (this._users ??= new UsersClient(this._options));
    }

    public get activeOrganization(): ActiveOrganizationClient {
        return (this._activeOrganization ??= new ActiveOrganizationClient(this._options));
    }

    public get devices(): DevicesClient {
        return (this._devices ??= new DevicesClient(this._options));
    }

    public get memberships(): MembershipsClient {
        return (this._memberships ??= new MembershipsClient(this._options));
    }

    public get notificationPreferences(): NotificationPreferencesClient {
        return (this._notificationPreferences ??= new NotificationPreferencesClient(this._options));
    }

    public get notifications(): NotificationsClient {
        return (this._notifications ??= new NotificationsClient(this._options));
    }

    public get operators(): OperatorsClient {
        return (this._operators ??= new OperatorsClient(this._options));
    }

    public get organizations(): OrganizationsClient {
        return (this._organizations ??= new OrganizationsClient(this._options));
    }

    public get realtime(): RealtimeClient {
        return (this._realtime ??= new RealtimeClient(this._options));
    }

    public get taskAttempts(): TaskAttemptsClient {
        return (this._taskAttempts ??= new TaskAttemptsClient(this._options));
    }

    public get tasks(): TasksClient {
        return (this._tasks ??= new TasksClient(this._options));
    }

    /**
     * Make a passthrough request using the SDK's configured auth, retry, logging, etc.
     * This is useful for making requests to endpoints not yet supported in the SDK.
     * The input can be a URL string, URL object, or Request object. Relative paths are resolved against the configured base URL.
     *
     * @param {Request | string | URL} input - The URL, path, or Request object.
     * @param {RequestInit} init - Standard fetch RequestInit options.
     * @param {core.PassthroughRequest.RequestOptions} requestOptions - Per-request overrides (timeout, retries, headers, abort signal).
     * @returns {Promise<Response>} A standard Response object.
     */
    public async fetch(
        input: Request | string | URL,
        init?: RequestInit,
        requestOptions?: core.PassthroughRequest.RequestOptions,
    ): Promise<Response> {
        return core.makePassthroughRequest(
            input,
            init,
            {
                baseUrl: this._options.baseUrl ?? this._options.environment,
                headers: this._options.headers,
                timeoutInSeconds: this._options.timeoutInSeconds,
                maxRetries: this._options.maxRetries,
                fetch: this._options.fetch,
                logging: this._options.logging,
                getAuthHeaders: async () => (await this._options.authProvider.getAuthRequest()).headers,
            },
            requestOptions,
        );
    }
}
