// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as NizamDashboard from "../../../index.js";

export declare namespace ArtifactsClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class ArtifactsClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<ArtifactsClient.Options>;

    constructor(options: ArtifactsClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * Artifacts across ALL of the caller's readable conversations — their own threads plus any thread shared into the organization — newest first unless `sort` says otherwise. This is the browse surface; `GET /conversations/{conversationId}/artifacts` is the complete, unpaginated list for ONE thread.
     *
     * `q` narrows the list to artifacts whose TITLE matches, accent-insensitively and stemmed for the organization's language — it is a filter, so `sort` still decides the order and a blank `q` is simply no filter. `scope` narrows by whose thread produced the artifact, and `type` by what kind of thing it is. Pagination is bidirectional (`starting_after` / `ending_before`); cursors are bound to the sort that minted them, so switching sorts restarts from the first page.
     *
     * @param {NizamDashboard.ListAllArtifactsRequest} request
     * @param {ArtifactsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link NizamDashboard.BadRequestError}
     * @throws {@link NizamDashboard.UnauthorizedError}
     * @throws {@link NizamDashboard.ForbiddenError}
     * @throws {@link NizamDashboard.TooManyRequestsError}
     * @throws {@link NizamDashboard.InternalServerError}
     *
     * @example
     *     await client.artifacts.listAllArtifacts({
     *         q: "<string>",
     *         starting_after: "Y3Vyc29yX25leHRfMDFKNVE=",
     *         ending_before: "Y3Vyc29yX25leHRfMDFKNVE="
     *     })
     */
    public listAllArtifacts(
        request: NizamDashboard.ListAllArtifactsRequest = {},
        requestOptions?: ArtifactsClient.RequestOptions,
    ): core.HttpResponsePromise<NizamDashboard.ListResponseArtifact> {
        return core.HttpResponsePromise.fromPromise(this.__listAllArtifacts(request, requestOptions));
    }

    private async __listAllArtifacts(
        request: NizamDashboard.ListAllArtifactsRequest = {},
        requestOptions?: ArtifactsClient.RequestOptions,
    ): Promise<core.WithRawResponse<NizamDashboard.ListResponseArtifact>> {
        const {
            q,
            type: type_,
            scope,
            sort,
            limit,
            starting_after: startingAfter,
            ending_before: endingBefore,
        } = request;
        const _queryParams: Record<string, unknown> = {
            q,
            type: Array.isArray(type_) ? type_.map((item) => item) : type_ != null ? type_ : undefined,
            scope: scope != null ? scope : undefined,
            sort: Array.isArray(sort) ? sort.map((item) => item) : sort != null ? sort : undefined,
            limit,
            starting_after: startingAfter,
            ending_before: endingBefore,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.NizamDashboardEnvironment.Production,
                "v1/artifacts",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as NizamDashboard.ListResponseArtifact, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new NizamDashboard.BadRequestError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 401:
                    throw new NizamDashboard.UnauthorizedError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 403:
                    throw new NizamDashboard.ForbiddenError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 429:
                    throw new NizamDashboard.TooManyRequestsError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 500:
                    throw new NizamDashboard.InternalServerError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.NizamDashboardError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/v1/artifacts");
    }

    /**
     * Returns every suggestion on the artifact, newest first, including already-resolved ones so the decision history stays readable. Check `stale` before offering Accept.
     *
     * @param {NizamDashboard.ListSuggestedEditsRequest} request
     * @param {ArtifactsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link NizamDashboard.UnauthorizedError}
     * @throws {@link NizamDashboard.ForbiddenError}
     * @throws {@link NizamDashboard.NotFoundError}
     * @throws {@link NizamDashboard.TooManyRequestsError}
     * @throws {@link NizamDashboard.InternalServerError}
     *
     * @example
     *     await client.artifacts.listSuggestedEdits({
     *         artifactId: "00000000-0000-0000-0000-000000000000"
     *     })
     */
    public listSuggestedEdits(
        request: NizamDashboard.ListSuggestedEditsRequest,
        requestOptions?: ArtifactsClient.RequestOptions,
    ): core.HttpResponsePromise<NizamDashboard.SuggestedEditList> {
        return core.HttpResponsePromise.fromPromise(this.__listSuggestedEdits(request, requestOptions));
    }

    private async __listSuggestedEdits(
        request: NizamDashboard.ListSuggestedEditsRequest,
        requestOptions?: ArtifactsClient.RequestOptions,
    ): Promise<core.WithRawResponse<NizamDashboard.SuggestedEditList>> {
        const { artifactId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.NizamDashboardEnvironment.Production,
                `v1/artifacts/${core.url.encodePathParam(artifactId)}/suggested-edits`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as NizamDashboard.SuggestedEditList, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new NizamDashboard.UnauthorizedError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 403:
                    throw new NizamDashboard.ForbiddenError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 404:
                    throw new NizamDashboard.NotFoundError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 429:
                    throw new NizamDashboard.TooManyRequestsError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 500:
                    throw new NizamDashboard.InternalServerError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.NizamDashboardError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/v1/artifacts/{artifactId}/suggested-edits",
        );
    }

    /**
     * Runs one AI review over the artifact's current version and returns the proposals it produced, newest first. Charges AI credits. Proposals the model could not anchor unambiguously in the document are discarded server-side, so an empty list is a normal outcome rather than an error.
     *
     * @param {NizamDashboard.GenerateSuggestionsRequest} request
     * @param {ArtifactsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link NizamDashboard.BadRequestError}
     * @throws {@link NizamDashboard.UnauthorizedError}
     * @throws {@link NizamDashboard.PaymentRequiredError}
     * @throws {@link NizamDashboard.ForbiddenError}
     * @throws {@link NizamDashboard.NotFoundError}
     * @throws {@link NizamDashboard.ConflictError}
     * @throws {@link NizamDashboard.UnprocessableEntityError}
     * @throws {@link NizamDashboard.TooManyRequestsError}
     * @throws {@link NizamDashboard.InternalServerError}
     *
     * @example
     *     await client.artifacts.generateSuggestedEdits({
     *         "Idempotency-Key": "9f1e6d2a-7c3b-4e5f-8a91-0b2c3d4e5f60",
     *         artifactId: "00000000-0000-0000-0000-000000000000",
     *         instruction: "Tighten the introduction and make the variable names clearer."
     *     })
     */
    public generateSuggestedEdits(
        request: NizamDashboard.GenerateSuggestionsRequest,
        requestOptions?: ArtifactsClient.RequestOptions,
    ): core.HttpResponsePromise<NizamDashboard.SuggestedEditList> {
        return core.HttpResponsePromise.fromPromise(this.__generateSuggestedEdits(request, requestOptions));
    }

    private async __generateSuggestedEdits(
        request: NizamDashboard.GenerateSuggestionsRequest,
        requestOptions?: ArtifactsClient.RequestOptions,
    ): Promise<core.WithRawResponse<NizamDashboard.SuggestedEditList>> {
        const { artifactId, "Idempotency-Key": idempotencyKey, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "Idempotency-Key": idempotencyKey }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.NizamDashboardEnvironment.Production,
                `v1/artifacts/${core.url.encodePathParam(artifactId)}/suggested-edits`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as NizamDashboard.SuggestedEditList, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new NizamDashboard.BadRequestError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 401:
                    throw new NizamDashboard.UnauthorizedError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 402:
                    throw new NizamDashboard.PaymentRequiredError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 403:
                    throw new NizamDashboard.ForbiddenError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 404:
                    throw new NizamDashboard.NotFoundError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 409:
                    throw new NizamDashboard.ConflictError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 422:
                    throw new NizamDashboard.UnprocessableEntityError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 429:
                    throw new NizamDashboard.TooManyRequestsError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 500:
                    throw new NizamDashboard.InternalServerError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.NizamDashboardError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/v1/artifacts/{artifactId}/suggested-edits",
        );
    }

    /**
     * Applies the model's text verbatim, appending a new artifact version. Fails with 409 `suggested_edit.already_resolved` if it was already decided, or 409 `suggested_edit.stale` if the artifact changed since the suggestion was made. No body.
     *
     * @param {NizamDashboard.AcceptSuggestedEditRequest} request
     * @param {ArtifactsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link NizamDashboard.UnauthorizedError}
     * @throws {@link NizamDashboard.ForbiddenError}
     * @throws {@link NizamDashboard.NotFoundError}
     * @throws {@link NizamDashboard.ConflictError}
     * @throws {@link NizamDashboard.TooManyRequestsError}
     * @throws {@link NizamDashboard.InternalServerError}
     *
     * @example
     *     await client.artifacts.acceptSuggestedEdit({
     *         artifactId: "00000000-0000-0000-0000-000000000000",
     *         editId: "00000000-0000-0000-0000-000000000000"
     *     })
     */
    public acceptSuggestedEdit(
        request: NizamDashboard.AcceptSuggestedEditRequest,
        requestOptions?: ArtifactsClient.RequestOptions,
    ): core.HttpResponsePromise<NizamDashboard.SuggestedEdit> {
        return core.HttpResponsePromise.fromPromise(this.__acceptSuggestedEdit(request, requestOptions));
    }

    private async __acceptSuggestedEdit(
        request: NizamDashboard.AcceptSuggestedEditRequest,
        requestOptions?: ArtifactsClient.RequestOptions,
    ): Promise<core.WithRawResponse<NizamDashboard.SuggestedEdit>> {
        const { artifactId, editId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.NizamDashboardEnvironment.Production,
                `v1/artifacts/${core.url.encodePathParam(artifactId)}/suggested-edits/${core.url.encodePathParam(editId)}/accept`,
            ),
            method: "POST",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as NizamDashboard.SuggestedEdit, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new NizamDashboard.UnauthorizedError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 403:
                    throw new NizamDashboard.ForbiddenError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 404:
                    throw new NizamDashboard.NotFoundError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 409:
                    throw new NizamDashboard.ConflictError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 429:
                    throw new NizamDashboard.TooManyRequestsError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 500:
                    throw new NizamDashboard.InternalServerError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.NizamDashboardError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/v1/artifacts/{artifactId}/suggested-edits/{editId}/accept",
        );
    }

    /**
     * Keeps the suggestion's location but substitutes your wording, appending a new artifact version. Resolves as `modified` rather than `accepted`, which records that the model's text needed fixing. Same 409s as accept.
     *
     * @param {NizamDashboard.ModifySuggestedEditRequest} request
     * @param {ArtifactsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link NizamDashboard.UnauthorizedError}
     * @throws {@link NizamDashboard.ForbiddenError}
     * @throws {@link NizamDashboard.NotFoundError}
     * @throws {@link NizamDashboard.ConflictError}
     * @throws {@link NizamDashboard.UnprocessableEntityError}
     * @throws {@link NizamDashboard.TooManyRequestsError}
     * @throws {@link NizamDashboard.InternalServerError}
     *
     * @example
     *     await client.artifacts.modifySuggestedEdit({
     *         artifactId: "00000000-0000-0000-0000-000000000000",
     *         editId: "00000000-0000-0000-0000-000000000000",
     *         content: "the shortest path from the source node"
     *     })
     */
    public modifySuggestedEdit(
        request: NizamDashboard.ModifySuggestedEditRequest,
        requestOptions?: ArtifactsClient.RequestOptions,
    ): core.HttpResponsePromise<NizamDashboard.SuggestedEdit> {
        return core.HttpResponsePromise.fromPromise(this.__modifySuggestedEdit(request, requestOptions));
    }

    private async __modifySuggestedEdit(
        request: NizamDashboard.ModifySuggestedEditRequest,
        requestOptions?: ArtifactsClient.RequestOptions,
    ): Promise<core.WithRawResponse<NizamDashboard.SuggestedEdit>> {
        const { artifactId, editId, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.NizamDashboardEnvironment.Production,
                `v1/artifacts/${core.url.encodePathParam(artifactId)}/suggested-edits/${core.url.encodePathParam(editId)}/modify`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as NizamDashboard.SuggestedEdit, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new NizamDashboard.UnauthorizedError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 403:
                    throw new NizamDashboard.ForbiddenError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 404:
                    throw new NizamDashboard.NotFoundError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 409:
                    throw new NizamDashboard.ConflictError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 422:
                    throw new NizamDashboard.UnprocessableEntityError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 429:
                    throw new NizamDashboard.TooManyRequestsError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 500:
                    throw new NizamDashboard.InternalServerError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.NizamDashboardError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/v1/artifacts/{artifactId}/suggested-edits/{editId}/modify",
        );
    }

    /**
     * Discards the suggestion without changing the artifact. Allowed even when the suggestion is stale — clearing a list the artifact has moved past must always be possible. No body.
     *
     * @param {NizamDashboard.RejectSuggestedEditRequest} request
     * @param {ArtifactsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link NizamDashboard.UnauthorizedError}
     * @throws {@link NizamDashboard.ForbiddenError}
     * @throws {@link NizamDashboard.NotFoundError}
     * @throws {@link NizamDashboard.ConflictError}
     * @throws {@link NizamDashboard.TooManyRequestsError}
     * @throws {@link NizamDashboard.InternalServerError}
     *
     * @example
     *     await client.artifacts.rejectSuggestedEdit({
     *         artifactId: "00000000-0000-0000-0000-000000000000",
     *         editId: "00000000-0000-0000-0000-000000000000"
     *     })
     */
    public rejectSuggestedEdit(
        request: NizamDashboard.RejectSuggestedEditRequest,
        requestOptions?: ArtifactsClient.RequestOptions,
    ): core.HttpResponsePromise<NizamDashboard.SuggestedEdit> {
        return core.HttpResponsePromise.fromPromise(this.__rejectSuggestedEdit(request, requestOptions));
    }

    private async __rejectSuggestedEdit(
        request: NizamDashboard.RejectSuggestedEditRequest,
        requestOptions?: ArtifactsClient.RequestOptions,
    ): Promise<core.WithRawResponse<NizamDashboard.SuggestedEdit>> {
        const { artifactId, editId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.NizamDashboardEnvironment.Production,
                `v1/artifacts/${core.url.encodePathParam(artifactId)}/suggested-edits/${core.url.encodePathParam(editId)}/reject`,
            ),
            method: "POST",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as NizamDashboard.SuggestedEdit, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new NizamDashboard.UnauthorizedError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 403:
                    throw new NizamDashboard.ForbiddenError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 404:
                    throw new NizamDashboard.NotFoundError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 409:
                    throw new NizamDashboard.ConflictError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 429:
                    throw new NizamDashboard.TooManyRequestsError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 500:
                    throw new NizamDashboard.InternalServerError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.NizamDashboardError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/v1/artifacts/{artifactId}/suggested-edits/{editId}/reject",
        );
    }

    /**
     * Returns the artifact header — type, title, language hint and current version number. Fetch the content separately by version.
     *
     * @param {NizamDashboard.GetArtifactRequest} request
     * @param {ArtifactsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link NizamDashboard.UnauthorizedError}
     * @throws {@link NizamDashboard.ForbiddenError}
     * @throws {@link NizamDashboard.NotFoundError}
     * @throws {@link NizamDashboard.TooManyRequestsError}
     * @throws {@link NizamDashboard.InternalServerError}
     *
     * @example
     *     await client.artifacts.getArtifact({
     *         id: "00000000-0000-0000-0000-000000000000"
     *     })
     */
    public getArtifact(
        request: NizamDashboard.GetArtifactRequest,
        requestOptions?: ArtifactsClient.RequestOptions,
    ): core.HttpResponsePromise<NizamDashboard.Artifact> {
        return core.HttpResponsePromise.fromPromise(this.__getArtifact(request, requestOptions));
    }

    private async __getArtifact(
        request: NizamDashboard.GetArtifactRequest,
        requestOptions?: ArtifactsClient.RequestOptions,
    ): Promise<core.WithRawResponse<NizamDashboard.Artifact>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.NizamDashboardEnvironment.Production,
                `v1/artifacts/${core.url.encodePathParam(id)}`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as NizamDashboard.Artifact, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new NizamDashboard.UnauthorizedError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 403:
                    throw new NizamDashboard.ForbiddenError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 404:
                    throw new NizamDashboard.NotFoundError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 429:
                    throw new NizamDashboard.TooManyRequestsError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 500:
                    throw new NizamDashboard.InternalServerError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.NizamDashboardError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/v1/artifacts/{id}");
    }

    /**
     * Removes the artifact from the conversation. The version history is retained internally for audit and erasure purposes but is no longer readable. No body.
     *
     * @param {NizamDashboard.DeleteArtifactRequest} request
     * @param {ArtifactsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link NizamDashboard.UnauthorizedError}
     * @throws {@link NizamDashboard.ForbiddenError}
     * @throws {@link NizamDashboard.NotFoundError}
     * @throws {@link NizamDashboard.TooManyRequestsError}
     * @throws {@link NizamDashboard.InternalServerError}
     *
     * @example
     *     await client.artifacts.deleteArtifact({
     *         id: "00000000-0000-0000-0000-000000000000"
     *     })
     */
    public deleteArtifact(
        request: NizamDashboard.DeleteArtifactRequest,
        requestOptions?: ArtifactsClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__deleteArtifact(request, requestOptions));
    }

    private async __deleteArtifact(
        request: NizamDashboard.DeleteArtifactRequest,
        requestOptions?: ArtifactsClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.NizamDashboardEnvironment.Production,
                `v1/artifacts/${core.url.encodePathParam(id)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new NizamDashboard.UnauthorizedError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 403:
                    throw new NizamDashboard.ForbiddenError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 404:
                    throw new NizamDashboard.NotFoundError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 429:
                    throw new NizamDashboard.TooManyRequestsError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 500:
                    throw new NizamDashboard.InternalServerError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.NizamDashboardError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "DELETE", "/v1/artifacts/{id}");
    }

    /**
     * Updates the title and language hint. The type and owning conversation are fixed at creation and cannot be changed.
     *
     * @param {NizamDashboard.UpdateArtifactRequest} request
     * @param {ArtifactsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link NizamDashboard.UnauthorizedError}
     * @throws {@link NizamDashboard.ForbiddenError}
     * @throws {@link NizamDashboard.NotFoundError}
     * @throws {@link NizamDashboard.UnprocessableEntityError}
     * @throws {@link NizamDashboard.TooManyRequestsError}
     * @throws {@link NizamDashboard.InternalServerError}
     *
     * @example
     *     await client.artifacts.updateArtifact({
     *         id: "00000000-0000-0000-0000-000000000000",
     *         title: "Dijkstra's Algorithm (annotated)",
     *         language: "python"
     *     })
     */
    public updateArtifact(
        request: NizamDashboard.UpdateArtifactRequest,
        requestOptions?: ArtifactsClient.RequestOptions,
    ): core.HttpResponsePromise<NizamDashboard.Artifact> {
        return core.HttpResponsePromise.fromPromise(this.__updateArtifact(request, requestOptions));
    }

    private async __updateArtifact(
        request: NizamDashboard.UpdateArtifactRequest,
        requestOptions?: ArtifactsClient.RequestOptions,
    ): Promise<core.WithRawResponse<NizamDashboard.Artifact>> {
        const { id, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.NizamDashboardEnvironment.Production,
                `v1/artifacts/${core.url.encodePathParam(id)}`,
            ),
            method: "PATCH",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as NizamDashboard.Artifact, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new NizamDashboard.UnauthorizedError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 403:
                    throw new NizamDashboard.ForbiddenError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 404:
                    throw new NizamDashboard.NotFoundError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 422:
                    throw new NizamDashboard.UnprocessableEntityError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 429:
                    throw new NizamDashboard.TooManyRequestsError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 500:
                    throw new NizamDashboard.InternalServerError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.NizamDashboardError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "PATCH", "/v1/artifacts/{id}");
    }

    /**
     * Returns the full history, newest first. A version marked with `restored_from_version_id` was produced by restoring an older one — history is append-only, so a restore adds a version rather than removing any.
     *
     * @param {NizamDashboard.ListArtifactVersionsRequest} request
     * @param {ArtifactsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link NizamDashboard.UnauthorizedError}
     * @throws {@link NizamDashboard.ForbiddenError}
     * @throws {@link NizamDashboard.NotFoundError}
     * @throws {@link NizamDashboard.TooManyRequestsError}
     * @throws {@link NizamDashboard.InternalServerError}
     *
     * @example
     *     await client.artifacts.listArtifactVersions({
     *         id: "00000000-0000-0000-0000-000000000000"
     *     })
     */
    public listArtifactVersions(
        request: NizamDashboard.ListArtifactVersionsRequest,
        requestOptions?: ArtifactsClient.RequestOptions,
    ): core.HttpResponsePromise<NizamDashboard.ArtifactVersionList> {
        return core.HttpResponsePromise.fromPromise(this.__listArtifactVersions(request, requestOptions));
    }

    private async __listArtifactVersions(
        request: NizamDashboard.ListArtifactVersionsRequest,
        requestOptions?: ArtifactsClient.RequestOptions,
    ): Promise<core.WithRawResponse<NizamDashboard.ArtifactVersionList>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.NizamDashboardEnvironment.Production,
                `v1/artifacts/${core.url.encodePathParam(id)}/versions`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as NizamDashboard.ArtifactVersionList, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new NizamDashboard.UnauthorizedError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 403:
                    throw new NizamDashboard.ForbiddenError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 404:
                    throw new NizamDashboard.NotFoundError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 429:
                    throw new NizamDashboard.TooManyRequestsError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 500:
                    throw new NizamDashboard.InternalServerError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.NizamDashboardError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/v1/artifacts/{id}/versions");
    }

    /**
     * Appends a new version with the supplied content and advances the artifact's current version. The previous content is retained.
     *
     * @param {NizamDashboard.SaveArtifactVersionRequest} request
     * @param {ArtifactsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link NizamDashboard.UnauthorizedError}
     * @throws {@link NizamDashboard.ForbiddenError}
     * @throws {@link NizamDashboard.NotFoundError}
     * @throws {@link NizamDashboard.UnprocessableEntityError}
     * @throws {@link NizamDashboard.TooManyRequestsError}
     * @throws {@link NizamDashboard.InternalServerError}
     *
     * @example
     *     await client.artifacts.saveArtifactVersion({
     *         id: "00000000-0000-0000-0000-000000000000",
     *         content: "def dijkstra(graph, start):\n    ...",
     *         created_by_message_id: "3c1e9b0a-2d4f-4a6b-8c0d-1e2f3a4b5c6d"
     *     })
     */
    public saveArtifactVersion(
        request: NizamDashboard.SaveArtifactVersionRequest,
        requestOptions?: ArtifactsClient.RequestOptions,
    ): core.HttpResponsePromise<NizamDashboard.ArtifactVersion> {
        return core.HttpResponsePromise.fromPromise(this.__saveArtifactVersion(request, requestOptions));
    }

    private async __saveArtifactVersion(
        request: NizamDashboard.SaveArtifactVersionRequest,
        requestOptions?: ArtifactsClient.RequestOptions,
    ): Promise<core.WithRawResponse<NizamDashboard.ArtifactVersion>> {
        const { id, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.NizamDashboardEnvironment.Production,
                `v1/artifacts/${core.url.encodePathParam(id)}/versions`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as NizamDashboard.ArtifactVersion, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new NizamDashboard.UnauthorizedError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 403:
                    throw new NizamDashboard.ForbiddenError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 404:
                    throw new NizamDashboard.NotFoundError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 422:
                    throw new NizamDashboard.UnprocessableEntityError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 429:
                    throw new NizamDashboard.TooManyRequestsError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 500:
                    throw new NizamDashboard.InternalServerError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.NizamDashboardError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v1/artifacts/{id}/versions");
    }

    /**
     * Returns the full text of one version. Content is always returned inline whatever the server's underlying storage, so a client needs no second code path for large artifacts.
     *
     * @param {NizamDashboard.GetArtifactVersionContentRequest} request
     * @param {ArtifactsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link NizamDashboard.UnauthorizedError}
     * @throws {@link NizamDashboard.ForbiddenError}
     * @throws {@link NizamDashboard.NotFoundError}
     * @throws {@link NizamDashboard.TooManyRequestsError}
     * @throws {@link NizamDashboard.InternalServerError}
     *
     * @example
     *     await client.artifacts.getArtifactVersionContent({
     *         id: "00000000-0000-0000-0000-000000000000",
     *         versionNumber: 1
     *     })
     */
    public getArtifactVersionContent(
        request: NizamDashboard.GetArtifactVersionContentRequest,
        requestOptions?: ArtifactsClient.RequestOptions,
    ): core.HttpResponsePromise<NizamDashboard.ArtifactContent> {
        return core.HttpResponsePromise.fromPromise(this.__getArtifactVersionContent(request, requestOptions));
    }

    private async __getArtifactVersionContent(
        request: NizamDashboard.GetArtifactVersionContentRequest,
        requestOptions?: ArtifactsClient.RequestOptions,
    ): Promise<core.WithRawResponse<NizamDashboard.ArtifactContent>> {
        const { id, versionNumber } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.NizamDashboardEnvironment.Production,
                `v1/artifacts/${core.url.encodePathParam(id)}/versions/${core.url.encodePathParam(versionNumber)}`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as NizamDashboard.ArtifactContent, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new NizamDashboard.UnauthorizedError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 403:
                    throw new NizamDashboard.ForbiddenError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 404:
                    throw new NizamDashboard.NotFoundError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 429:
                    throw new NizamDashboard.TooManyRequestsError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 500:
                    throw new NizamDashboard.InternalServerError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.NizamDashboardError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/v1/artifacts/{id}/versions/{versionNumber}",
        );
    }

    /**
     * Appends a NEW version cloning the addressed one's content, and points the artifact at it. This is not a rollback: nothing is removed, and the restore is itself recorded in the history (the new version carries `restored_from_version_id`). No body.
     *
     * @param {NizamDashboard.RestoreArtifactVersionRequest} request
     * @param {ArtifactsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link NizamDashboard.UnauthorizedError}
     * @throws {@link NizamDashboard.ForbiddenError}
     * @throws {@link NizamDashboard.NotFoundError}
     * @throws {@link NizamDashboard.TooManyRequestsError}
     * @throws {@link NizamDashboard.InternalServerError}
     *
     * @example
     *     await client.artifacts.restoreArtifactVersion({
     *         id: "00000000-0000-0000-0000-000000000000",
     *         versionNumber: 1
     *     })
     */
    public restoreArtifactVersion(
        request: NizamDashboard.RestoreArtifactVersionRequest,
        requestOptions?: ArtifactsClient.RequestOptions,
    ): core.HttpResponsePromise<NizamDashboard.ArtifactVersion> {
        return core.HttpResponsePromise.fromPromise(this.__restoreArtifactVersion(request, requestOptions));
    }

    private async __restoreArtifactVersion(
        request: NizamDashboard.RestoreArtifactVersionRequest,
        requestOptions?: ArtifactsClient.RequestOptions,
    ): Promise<core.WithRawResponse<NizamDashboard.ArtifactVersion>> {
        const { id, versionNumber } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.NizamDashboardEnvironment.Production,
                `v1/artifacts/${core.url.encodePathParam(id)}/versions/${core.url.encodePathParam(versionNumber)}/restore`,
            ),
            method: "POST",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as NizamDashboard.ArtifactVersion, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new NizamDashboard.UnauthorizedError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 403:
                    throw new NizamDashboard.ForbiddenError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 404:
                    throw new NizamDashboard.NotFoundError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 429:
                    throw new NizamDashboard.TooManyRequestsError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 500:
                    throw new NizamDashboard.InternalServerError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.NizamDashboardError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/v1/artifacts/{id}/versions/{versionNumber}/restore",
        );
    }

    /**
     * Returns every artifact produced in the conversation, newest first. Complete, not paginated — a thread holds a handful. Requires read access to the conversation.
     *
     * @param {NizamDashboard.ListArtifactsRequest} request
     * @param {ArtifactsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link NizamDashboard.UnauthorizedError}
     * @throws {@link NizamDashboard.ForbiddenError}
     * @throws {@link NizamDashboard.NotFoundError}
     * @throws {@link NizamDashboard.TooManyRequestsError}
     * @throws {@link NizamDashboard.InternalServerError}
     *
     * @example
     *     await client.artifacts.listArtifacts({
     *         conversationId: "00000000-0000-0000-0000-000000000000"
     *     })
     */
    public listArtifacts(
        request: NizamDashboard.ListArtifactsRequest,
        requestOptions?: ArtifactsClient.RequestOptions,
    ): core.HttpResponsePromise<NizamDashboard.ArtifactList> {
        return core.HttpResponsePromise.fromPromise(this.__listArtifacts(request, requestOptions));
    }

    private async __listArtifacts(
        request: NizamDashboard.ListArtifactsRequest,
        requestOptions?: ArtifactsClient.RequestOptions,
    ): Promise<core.WithRawResponse<NizamDashboard.ArtifactList>> {
        const { conversationId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.NizamDashboardEnvironment.Production,
                `v1/conversations/${core.url.encodePathParam(conversationId)}/artifacts`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as NizamDashboard.ArtifactList, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new NizamDashboard.UnauthorizedError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 403:
                    throw new NizamDashboard.ForbiddenError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 404:
                    throw new NizamDashboard.NotFoundError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 429:
                    throw new NizamDashboard.TooManyRequestsError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 500:
                    throw new NizamDashboard.InternalServerError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.NizamDashboardError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/v1/conversations/{conversationId}/artifacts",
        );
    }

    /**
     * Creates an artifact in the conversation at version 1. Only the conversation's owner may create artifacts in it; anyone else gets 404, indistinguishable from a missing conversation.
     *
     * @param {NizamDashboard.CreateArtifactRequest} request
     * @param {ArtifactsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link NizamDashboard.BadRequestError}
     * @throws {@link NizamDashboard.UnauthorizedError}
     * @throws {@link NizamDashboard.ForbiddenError}
     * @throws {@link NizamDashboard.NotFoundError}
     * @throws {@link NizamDashboard.ConflictError}
     * @throws {@link NizamDashboard.UnprocessableEntityError}
     * @throws {@link NizamDashboard.TooManyRequestsError}
     * @throws {@link NizamDashboard.InternalServerError}
     *
     * @example
     *     await client.artifacts.createArtifact({
     *         "Idempotency-Key": "9f1e6d2a-7c3b-4e5f-8a91-0b2c3d4e5f60",
     *         conversationId: "00000000-0000-0000-0000-000000000000",
     *         type: "document",
     *         title: "Dijkstra's Algorithm",
     *         language: "python",
     *         content: "def dijkstra(graph, start):\n    ...",
     *         created_by_message_id: "3c1e9b0a-2d4f-4a6b-8c0d-1e2f3a4b5c6d"
     *     })
     */
    public createArtifact(
        request: NizamDashboard.CreateArtifactRequest,
        requestOptions?: ArtifactsClient.RequestOptions,
    ): core.HttpResponsePromise<NizamDashboard.Artifact> {
        return core.HttpResponsePromise.fromPromise(this.__createArtifact(request, requestOptions));
    }

    private async __createArtifact(
        request: NizamDashboard.CreateArtifactRequest,
        requestOptions?: ArtifactsClient.RequestOptions,
    ): Promise<core.WithRawResponse<NizamDashboard.Artifact>> {
        const { conversationId, "Idempotency-Key": idempotencyKey, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "Idempotency-Key": idempotencyKey }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.NizamDashboardEnvironment.Production,
                `v1/conversations/${core.url.encodePathParam(conversationId)}/artifacts`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as NizamDashboard.Artifact, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new NizamDashboard.BadRequestError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 401:
                    throw new NizamDashboard.UnauthorizedError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 403:
                    throw new NizamDashboard.ForbiddenError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 404:
                    throw new NizamDashboard.NotFoundError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 409:
                    throw new NizamDashboard.ConflictError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 422:
                    throw new NizamDashboard.UnprocessableEntityError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 429:
                    throw new NizamDashboard.TooManyRequestsError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 500:
                    throw new NizamDashboard.InternalServerError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.NizamDashboardError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/v1/conversations/{conversationId}/artifacts",
        );
    }
}
