// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "00000000-0000-0000-0000-000000000000",
 *         reason: "shift_end"
 *     }
 */
export interface CloseAssignmentRequest {
    id: string;
    /** Why the assignment is being closed. */
    reason: CloseAssignmentRequest.Reason;
}

export namespace CloseAssignmentRequest {
    /** Why the assignment is being closed. */
    export const Reason = {
        ShiftEnd: "shift_end",
        AssetMaintenance: "asset_maintenance",
        OperatorOffDuty: "operator_off_duty",
        Incident: "incident",
        SoftwareUpdate: "software_update",
        Reassigned: "reassigned",
        ContractEnded: "contract_ended",
        ManualClose: "manual_close",
    } as const;
    export type Reason = (typeof Reason)[keyof typeof Reason];
}
