// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         jobId: "00000000-0000-0000-0000-000000000000"
 *     }
 */
export interface CreateImportReportUrlRequest {
    jobId: string;
}
