// This file was auto-generated by Fern from our API Definition.

import type * as NizamMerchant from "../../../../index.js";

/**
 * @example
 *     {
 *         subject_type: "<string>",
 *         subject_id: "00000000-0000-0000-0000-000000000000",
 *         starting_after: "Y3Vyc29yX25leHRfMDFKNVE=",
 *         ending_before: "Y3Vyc29yX25leHRfMDFKNVE="
 *     }
 */
export interface ListFilesRequest {
    /** Filter by file kind. Comma-separated; matched case-insensitively. */
    kind?: NizamMerchant.ListFilesRequestKindItem | NizamMerchant.ListFilesRequestKindItem[];
    /** Filter by lifecycle status. Comma-separated; matched case-insensitively. */
    status?: NizamMerchant.ListFilesRequestStatusItem | NizamMerchant.ListFilesRequestStatusItem[];
    /** Filter by the documented entity's type (pairs with `subject_id`). */
    subject_type?: string;
    /** Filter by the documented entity's id (requires `subject_type`). */
    subject_id?: string;
    /** Sort order. Allowed fields: `created_at`. Append `:asc` or `:desc` to each field (direction required, e.g. `created_at:desc`), comma-separated for multi-sort; unknown fields or directions are rejected with `400 validation_failed`. */
    sort?: NizamMerchant.ListFilesRequestSortItem | NizamMerchant.ListFilesRequestSortItem[];
    /** Page size. Default 20, maximum 100. Out-of-range values are silently clamped; the response body's `limit` field reflects what was applied. */
    limit?: number;
    /** Opaque cursor — return the page starting strictly after this entity in the sort order. Mutually exclusive with `ending_before`. */
    starting_after?: string;
    /** Opaque cursor — return the page ending strictly before this entity in the sort order. Mutually exclusive with `starting_after`. */
    ending_before?: string;
}
