// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         "Idempotency-Key": "9f1e6d2a-7c3b-4e5f-8a91-0b2c3d4e5f60",
 *         title: "Trip planning",
 *         visibility: "private"
 *     }
 */
export interface CreateConversationRequest {
    /** Optional. Supply a UUID (canonical 8-4-4-4-12 form; lowercase v4 recommended) to make this operation idempotent: the same key on a retry replays the original outcome instead of creating a second resource. 2xx successes and deliberate 4xx domain rejections are cached and replayed for 24h when the request body matches; transient 5xx responses are never cached, so a retry with the same key re-executes. A malformed key is rejected with 400 `idempotency.invalid_key`; reusing a key with a different request body is 409 `idempotency.key_conflict`; a key still in flight is 409 `idempotency.in_progress`. Omit the header and the operation behaves like any other write. */
    "Idempotency-Key"?: string;
    /** Optional title; a conversation is untitled until named. */
    title?: string;
    /** Who else in the org may read it (default private). */
    visibility?: CreateConversationRequest.Visibility;
}

export namespace CreateConversationRequest {
    /** Who else in the org may read it (default private). */
    export const Visibility = {
        Private: "private",
        Workspace: "workspace",
        Org: "org",
    } as const;
    export type Visibility = (typeof Visibility)[keyof typeof Visibility];
}
