// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         conversationId: "00000000-0000-0000-0000-000000000000",
 *         shareId: "00000000-0000-0000-0000-000000000000"
 *     }
 */
export interface RevokeConversationShareRequest {
    conversationId: string;
    shareId: string;
}
