// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "00000000-0000-0000-0000-000000000000",
 *         title: "Q3 logistics review",
 *         visibility: "workspace"
 *     }
 */
export interface UpdateConversationRequest {
    id: string;
    /** New title; "" clears it, omit to leave unchanged. */
    title?: string;
    /** New visibility; omit to leave unchanged. */
    visibility?: UpdateConversationRequest.Visibility;
}

export namespace UpdateConversationRequest {
    /** New visibility; omit to leave unchanged. */
    export const Visibility = {
        Private: "private",
        Workspace: "workspace",
        Org: "org",
    } as const;
    export type Visibility = (typeof Visibility)[keyof typeof Visibility];
}
