// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         "Idempotency-Key": "9f1e6d2a-7c3b-4e5f-8a91-0b2c3d4e5f60",
 *         organization_id: "8f55f0eb-7d3a-4f2c-9c8d-a1b2c3d4e5f6",
 *         email: "ali@nizam.ai",
 *         role: "admin"
 *     }
 *
 * @example
 *     {
 *         "Idempotency-Key": "9f1e6d2a-7c3b-4e5f-8a91-0b2c3d4e5f60",
 *         organization_id: "8f55f0eb-7d3a-4f2c-9c8d-a1b2c3d4e5f6",
 *         email: "jordan@example.com",
 *         role: "dispatcher",
 *         ttl_days: 14
 *     }
 *
 * @example
 *     {
 *         "Idempotency-Key": "9f1e6d2a-7c3b-4e5f-8a91-0b2c3d4e5f60",
 *         organization_id: "8f55f0eb-7d3a-4f2c-9c8d-a1b2c3d4e5f6",
 *         email: "auditor@partner.example",
 *         role: "viewer",
 *         ttl_days: 3
 *     }
 */
export interface CreateInviteRequest {
    /** Optional. Supply a UUID (canonical 8-4-4-4-12 form; lowercase v4 recommended) to make this operation idempotent: the same key on a retry replays the original outcome instead of creating a second resource. 2xx successes and deliberate 4xx domain rejections are cached and replayed for 24h when the request body matches; transient 5xx responses are never cached, so a retry with the same key re-executes. A malformed key is rejected with 400 `idempotency.invalid_key`; reusing a key with a different request body is 409 `idempotency.key_conflict`; a key still in flight is 409 `idempotency.in_progress`. Omit the header and the operation behaves like any other write. */
    "Idempotency-Key"?: string;
    /** Organization the invite is for. */
    organization_id: string;
    /** Recipient email. */
    email: string;
    /** Role the recipient will hold after acceptance. `operator` is not invitable here — operators join through driver enrolment. */
    role: CreateInviteRequest.Role;
    /** TTL in days. Defaults to 7. */
    ttl_days?: number;
}

export namespace CreateInviteRequest {
    /** Role the recipient will hold after acceptance. `operator` is not invitable here — operators join through driver enrolment. */
    export const Role = {
        Admin: "admin",
        Dispatcher: "dispatcher",
        Manager: "manager",
        Staff: "staff",
        Viewer: "viewer",
        BillingAdmin: "billing_admin",
        Operator: "operator",
    } as const;
    export type Role = (typeof Role)[keyof typeof Role];
}
