// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         domain: "acme.com"
 *     }
 */
export interface LookupSsoRouteRequest {
    /** Email domain (the part after `@`), lowercase. */
    domain: string;
}
