// This file was auto-generated by Fern from our API Definition.

import type * as NizamOperatorRuntime from "../index.js";

/**
 * An immutable configuration version of an agent persona.
 */
export interface AgentProfileVersion {
    /** Monotonic version number. */
    version_number?: number | undefined;
    model_settings?: NizamOperatorRuntime.AgentModelSettings | undefined;
    /** Platform base prompt (from the category), frozen at author time. */
    base_system_prompt?: string | undefined;
    /** The org's custom instructions. */
    instructions?: string | undefined;
    /** The composed prompt the engine uses (base + instructions). */
    effective_system_prompt?: string | undefined;
    /** Tool names the persona may use. */
    tools?: string[] | undefined;
    /** Knowledge collection ids the persona grounds on. */
    knowledge_collection_ids?: string[] | undefined;
    autonomy?: NizamOperatorRuntime.AgentAutonomyPolicy | undefined;
    /** When this version was authored. */
    created_at?: string | undefined;
}
