// This file was auto-generated by Fern from our API Definition.

/**
 * One field-level entry inside a 422 validation problem.
 */
export interface ApiFieldError {
    /** Dot-notated JSON path matching the request shape. */
    field: string;
    /** Stable machine-readable code. */
    code: string;
    /** Human-readable detail (English). */
    message: string;
}
