// This file was auto-generated by Fern from our API Definition.

/**
 * The full text of one artifact version.
 */
export interface ArtifactContent {
    /** The artifact this content belongs to. */
    artifact_id: string;
    /** The version number this content is of. */
    version_number: number;
    /** The version's full text. Returned inline whatever the server's underlying storage — a caller never needs a second code path for large artifacts. */
    content: string;
    /** Object type discriminator. */
    object: ArtifactContent.Object_;
}

export namespace ArtifactContent {
    /** Object type discriminator. */
    export const Object_ = {
        ArtifactContent: "artifact_content",
    } as const;
    export type Object_ = (typeof Object_)[keyof typeof Object_];
}
