// This file was auto-generated by Fern from our API Definition.

/**
 * Start a new assistant conversation.
 */
export interface CreateConversationRequest {
    /** Optional title; a conversation is untitled until named. */
    title?: string | undefined;
    /** Who else in the org may read it (default private). */
    visibility?: CreateConversationRequest.Visibility | undefined;
}

export namespace CreateConversationRequest {
    /** Who else in the org may read it (default private). */
    export const Visibility = {
        Private: "private",
        Workspace: "workspace",
        Org: "org",
    } as const;
    export type Visibility = (typeof Visibility)[keyof typeof Visibility];
}
