// This file was auto-generated by Fern from our API Definition.

import type * as NizamOperatorRuntime from "../index.js";

/**
 * Create a new operator. The kind discriminator selects the variant.
 */
export type CreateOperatorRequest =
    | NizamOperatorRuntime.CreateOperatorRequest.Human
    | NizamOperatorRuntime.CreateOperatorRequest.Autonomous
    | NizamOperatorRuntime.CreateOperatorRequest.Teleoperated;

export namespace CreateOperatorRequest {
    export interface Human extends NizamOperatorRuntime.CreateHumanOperatorRequest {
        kind: "human";
    }

    export interface Autonomous extends NizamOperatorRuntime.CreateAutonomousOperatorRequest {
        kind: "autonomous";
    }

    export interface Teleoperated extends NizamOperatorRuntime.CreateTeleoperatedOperatorRequest {
        kind: "teleoperated";
    }
}
