// This file was auto-generated by Fern from our API Definition.

/**
 * A registered push device (the token is never returned).
 */
export interface Device {
    /** Device id. */
    id: string;
    /** Push transport. */
    platform: Device.Platform;
    /** Registration lifecycle. */
    status: Device.Status;
    /** When the device was first registered. */
    registered_at: string;
    /** When the registration was last refreshed (last seen). */
    last_seen_at: string;
    /** Object type discriminator. */
    object: Device.Object_;
}

export namespace Device {
    /** Push transport. */
    export const Platform = {
        Ios: "ios",
        Android: "android",
        Web: "web",
    } as const;
    export type Platform = (typeof Platform)[keyof typeof Platform];
    /** Registration lifecycle. */
    export const Status = {
        Active: "active",
        Suspended: "suspended",
        Inactive: "inactive",
        Expired: "expired",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
    /** Object type discriminator. */
    export const Object_ = {
        Device: "device",
    } as const;
    export type Object_ = (typeof Object_)[keyof typeof Object_];
}
