// This file was auto-generated by Fern from our API Definition.

import type * as NizamOperatorRuntime from "../index.js";

/**
 * An organization's erasure requests, newest first.
 */
export interface ErasureRequestList {
    /** The organization's requests, newest first. */
    erasure_requests: NizamOperatorRuntime.ErasureRequest[];
    object: ErasureRequestList.Object_;
}

export namespace ErasureRequestList {
    export const Object_ = {
        AssistantErasureRequestList: "assistant_erasure_request_list",
    } as const;
    export type Object_ = (typeof Object_)[keyof typeof Object_];
}
