// This file was auto-generated by Fern from our API Definition.

/**
 * A presigned PUT for one part. Send the raw part bytes; repeat `headers` verbatim; keep the response's `ETag` header for completion.
 */
export interface FileUploadPart {
    /** 1-based part number. */
    part_number?: number | undefined;
    /** Presigned URL to PUT the part's bytes to. */
    url?: string | undefined;
    /** Headers that were signed into the URL; the PUT must repeat them verbatim. */
    headers?: Record<string, string> | undefined;
    /** When this URL stops working (re-issue via resume). */
    url_expires_at?: string | undefined;
}
