// This file was auto-generated by Fern from our API Definition.

/**
 * Per-interaction-type counts and token totals within the window.
 */
export interface InteractionTypeStatsResponse {
    /** The interaction type. */
    type?: string | undefined;
    /** Interactions of this type. */
    count?: number | undefined;
    /** Prompt tokens. */
    input_tokens?: number | undefined;
    /** Generated tokens. */
    output_tokens?: number | undefined;
    /** Hidden reasoning tokens. */
    reasoning_tokens?: number | undefined;
    /** Context-cache read tokens. */
    cached_tokens?: number | undefined;
}
