// This file was auto-generated by Fern from our API Definition.

/**
 * Tenant-admin invite payload.
 */
export interface InviteUserRequest {
    /** Recipient email. */
    email: string;
    /** Display name (optional). */
    name?: string | undefined;
}
