// This file was auto-generated by Fern from our API Definition.

/**
 * An invitation to join an organization.
 */
export interface Invite {
    /** Stable UUID of this invite. */
    id: string;
    /** Organization the invite confers membership in. */
    organization_id: string;
    /** Recipient email: canonical lowercase form. Exactly one of `invited_email` / `invited_phone` is set — staff invitations carry the email, operator (driver) enrolments the phone. */
    invited_email?: string | undefined;
    /** Recipient phone in E.164 form, for operator (driver) enrolments. Exactly one of `invited_email` / `invited_phone` is set. */
    invited_phone?: string | undefined;
    /** Role the recipient will hold after acceptance. */
    role: Invite.Role;
    /** Lifecycle status. */
    status: Invite.Status;
    /** When the invite expires. Recipients must accept before then. */
    expires_at: string;
    /** When the invitation was accepted, if it was. */
    accepted_at?: string | undefined;
    /** When the invitation was revoked, if it was. */
    revoked_at?: string | undefined;
    /** Bearer secret used to redeem the invite. Returned only on POST /v1/invites, where the sender sees it once; absent from every other response, including the lifecycle verbs. */
    token?: string | undefined;
    /** Lifecycle statuses an administrator can move this invitation to next, the wire projection of the server-side transition matrix, derived from `status`. Empty once the invitation is settled. Acceptance and expiry never appear: they are the recipient's act and the clock's, not an administrator's. */
    allowed_transitions: Invite.AllowedTransitions.Item[];
    /** Object type discriminator. */
    object: Invite.Object_;
}

export namespace Invite {
    /** Role the recipient will hold after acceptance. */
    export const Role = {
        Admin: "admin",
        Dispatcher: "dispatcher",
        Manager: "manager",
        Staff: "staff",
        Viewer: "viewer",
        BillingAdmin: "billing_admin",
        Operator: "operator",
    } as const;
    export type Role = (typeof Role)[keyof typeof Role];
    /** Lifecycle status. */
    export const Status = {
        Pending: "pending",
        Accepted: "accepted",
        Expired: "expired",
        Revoked: "revoked",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
    export type AllowedTransitions = AllowedTransitions.Item[];

    export namespace AllowedTransitions {
        /** A status an administrator may move this invitation to. */
        export const Item = {
            Pending: "pending",
            Accepted: "accepted",
            Expired: "expired",
            Revoked: "revoked",
        } as const;
        export type Item = (typeof Item)[keyof typeof Item];
    }

    /** Object type discriminator. */
    export const Object_ = {
        Invite: "invite",
    } as const;
    export type Object_ = (typeof Object_)[keyof typeof Object_];
}
