// This file was auto-generated by Fern from our API Definition.

/**
 * Acknowledgement that a job was submitted to its engine.
 */
export interface JobSubmission {
    /** The created job — poll/cancel it via /v1/jobs/{id}. */
    job_id?: string | undefined;
    object?: JobSubmission.Object_ | undefined;
}

export namespace JobSubmission {
    export const Object_ = {
        JobSubmission: "job_submission",
    } as const;
    export type Object_ = (typeof Object_)[keyof typeof Object_];
}
