// This file was auto-generated by Fern from our API Definition.

/**
 * One knowledge source a grounded assistant reply cites, in presentation order.
 */
export interface MessageCitation {
    /** What kind of source this citation points at. */
    subject_type?: MessageCitation.SubjectType | undefined;
    /** The source's id within its own resource — for knowledge_document, the knowledge base document id. */
    subject_id?: string | undefined;
    /** The source document's title, as retrieved. */
    title?: string | undefined;
    /** The cited excerpt, as retrieved (truncated for display). */
    snippet?: string | undefined;
    /** Retrieval relevance score — an ordering signal on the retrieval pipeline's own scale, not a calibrated probability. */
    score?: number | undefined;
    /** 1-based presentation order of this citation within the reply. */
    rank?: number | undefined;
}

export namespace MessageCitation {
    /** What kind of source this citation points at. */
    export const SubjectType = {
        KnowledgeDocument: "knowledge_document",
    } as const;
    export type SubjectType = (typeof SubjectType)[keyof typeof SubjectType];
}
