// This file was auto-generated by Fern from our API Definition.

import type * as NizamOperatorRuntime from "../index.js";

/**
 * Inbox segment-badge counts (server-derived).
 */
export interface NotificationCounts {
    /** Active (non-archived) notifications. */
    total?: number | undefined;
    /** Active unread notifications. */
    unread?: number | undefined;
    /** Archived ("Done") notifications. */
    archived?: number | undefined;
    /** Per-category active counts; categories with no active row are omitted. */
    categories?: NizamOperatorRuntime.NotificationCategoryCount[] | undefined;
    /** Object type discriminator. */
    object?: NotificationCounts.Object_ | undefined;
}

export namespace NotificationCounts {
    /** Object type discriminator. */
    export const Object_ = {
        NotificationCounts: "notification_counts",
    } as const;
    export type Object_ = (typeof Object_)[keyof typeof Object_];
}
