// This file was auto-generated by Fern from our API Definition.

/**
 * Schedule a merchant payout for a future run.
 */
export interface ScheduleMerchantPayoutRequest {
    /** When the payout should run. */
    scheduled_for: string;
}
