// This file was auto-generated by Fern from our API Definition.

/**
 * One directory-group → membership-role rule.
 */
export interface SsoGroupMapping {
    /** Asserted group name, matched exactly. */
    group?: string | undefined;
    /** Membership role the group grants. */
    role?: SsoGroupMapping.Role | undefined;
}

export namespace SsoGroupMapping {
    /** Membership role the group grants. */
    export const Role = {
        Admin: "admin",
        Dispatcher: "dispatcher",
        Manager: "manager",
        Staff: "staff",
        Viewer: "viewer",
        BillingAdmin: "billing_admin",
        Operator: "operator",
    } as const;
    export type Role = (typeof Role)[keyof typeof Role];
}
