// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         "Idempotency-Key": "9f1e6d2a-7c3b-4e5f-8a91-0b2c3d4e5f60",
 *         projectId: "00000000-0000-0000-0000-000000000000",
 *         document_id: "3f1c9a54-6b7d-4e21-8c0f-9a2b3c4d5e6f"
 *     }
 */
export interface AttachAssistantProjectDocumentRequest {
    projectId: string;
    /** Optional. Supply a UUID (canonical 8-4-4-4-12 form; lowercase v4 recommended) to make this operation idempotent: the same key on a retry replays the original outcome instead of creating a second resource. 2xx successes and deliberate 4xx domain rejections are cached and replayed for 24h when the request body matches; transient 5xx responses are never cached, so a retry with the same key re-executes. A malformed key is rejected with 400 `idempotency.invalid_key`; reusing a key with a different request body is 409 `idempotency.key_conflict`; a key still in flight is 409 `idempotency.in_progress`. Omit the header and the operation behaves like any other write. */
    "Idempotency-Key"?: string;
    /** Id of a knowledge document in the caller's organization. */
    document_id: string;
}
