// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "00000000-0000-0000-0000-000000000000",
 *         name: "Acme Logistics",
 *         slug: "acme-logistics",
 *         business_category: "third_party_logistics",
 *         phone: "+15551234567",
 *         country: "US",
 *         timezone: "America/Los_Angeles"
 *     }
 */
export interface UpdateOrganizationRequest {
    id: string;
    /** New display name. Omit to leave unchanged. */
    name?: string;
    /** New URL-safe slug. Cross-tenant unique. Omit to leave unchanged. */
    slug?: string;
    /** New business category — lowercase slug from /v1/lookups/business-categories. Omit to leave unchanged. */
    business_category?: string;
    /** New contact phone in E.164 format. Omit to leave unchanged. */
    phone?: string;
    /** New ISO 3166-1 alpha-2 country code. Omit to leave unchanged. */
    country?: string;
    /** New IANA timezone identifier. Omit to leave unchanged. */
    timezone?: string;
}
