// This file was auto-generated by Fern from our API Definition.

import type * as NizamDashboard from "../../../../index.js";

/**
 * @example
 *     {
 *         q: "<string>",
 *         starting_after: "Y3Vyc29yX25leHRfMDFKNVE=",
 *         ending_before: "Y3Vyc29yX25leHRfMDFKNVE="
 *     }
 */
export interface ListOperatorsRequest {
    /** Filter by kind. Comma-separated; matched case-insensitively. */
    kind?: NizamDashboard.ListOperatorsRequestKindItem | NizamDashboard.ListOperatorsRequestKindItem[];
    /** Free-text search over the display name. Narrows the page; the order is unchanged. */
    q?: string;
    /** Page size. Default 20, maximum 100. Out-of-range values are silently clamped; the response body's `limit` field reflects what was applied. */
    limit?: number;
    /** Opaque cursor: return the page starting strictly after this entity in the sort order. Mutually exclusive with `ending_before`. */
    starting_after?: string;
    /** Opaque cursor: return the page ending strictly before this entity in the sort order. Mutually exclusive with `starting_after`. */
    ending_before?: string;
}
