// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "00000000-0000-0000-0000-000000000000",
 *         version: "7.4"
 *     }
 */
export interface RecordSoftwareVersionRequest {
    id: string;
    /** The build now running on this instance. Free-form: the platform records what the vendor calls it and never parses or orders it. */
    version: string;
}
