// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "00000000-0000-0000-0000-000000000000",
 *         merchant_payout_id: "7a6b5c4d-3e2f-1a0b-9c8d-7e6f5a4b3c2d"
 *     }
 */
export interface ReconcileCodCollectionRequest {
    id: string;
    /** The merchant payout to reconcile this collection into. */
    merchant_payout_id: string;
}
