// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         token: "kZ7q2vY8sN1pR4tW6xA0bC3dE5fG7hJ9kL1mN3oP5qR",
 *         csr: "-----BEGIN CERTIFICATE REQUEST-----\nMIIBHTCBxAIBADBiMQswCQYDVQQGEwJVUzE...\n-----END CERTIFICATE REQUEST-----"
 *     }
 */
export interface EnrolWorkloadRequest {
    /** The single-use enrolment voucher, as issued to whoever commissioned the machine. Presented exactly once. */
    token: string;
    /** PEM-encoded PKCS#10 certificate signing request. The private key is generated on the device and never leaves it; this request's self-signature is the proof of possession. Elliptic curve P-256/P-384/P-521 or RSA of at least 3072 bits. */
    csr: string;
}
