// This file was auto-generated by Fern from our API Definition.

export const ListConversationsRequestStatusItem = {
    Active: "active",
    Archived: "archived",
} as const;
export type ListConversationsRequestStatusItem =
    (typeof ListConversationsRequestStatusItem)[keyof typeof ListConversationsRequestStatusItem];
