// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         plan_code: "enterprise"
 *     }
 */
export interface PreviewSubscriptionPlanChangeRequest {
    /** The code of the plan to price. */
    plan_code: string;
}
