// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         from: "2026-05-20T14:00:00Z",
 *         to: "2026-05-20T14:00:00Z"
 *     }
 */
export interface GetAssistantStatsRequest {
    /** Window start (inclusive). Defaults to 30 days before now. */
    from?: string;
    /** Window end (exclusive). Defaults to now. */
    to?: string;
}
