// This file was auto-generated by Fern from our API Definition.

import type * as NizamDashboard from "../../../../index.js";

/**
 * @example
 *     {
 *         enabled: true,
 *         persona_allowlist: ["3f2504e0-4f89-11d3-9a0c-0305e82c3301"],
 *         retention_days: 90,
 *         features: {
 *             rag: true,
 *             tools: true,
 *             attachments: true,
 *             sharing: true,
 *             "export": true,
 *             auto_title: true,
 *             follow_ups: true
 *         },
 *         instructions: "Always confirm the delivery address before rescheduling.",
 *         safety: {
 *             input: "block",
 *             output: "block",
 *             rag: "flag",
 *             tools: "flag",
 *             attachments: "flag",
 *             judge: false
 *         },
 *         reasoning_capture: false,
 *         eval_consent: false
 *     }
 */
export interface UpdateAssistantSettingsRequest {
    /** Enable/disable the assistant for the org. */
    enabled?: boolean;
    /** Allowed persona ids (empty = no restriction). */
    persona_allowlist?: string[];
    /** Conversation retention in days (positive). */
    retention_days?: number;
    features?: NizamDashboard.AssistantFeatureToggles;
    /** Org instructions; "" clears them, omit to leave unchanged. */
    instructions?: string;
    safety?: NizamDashboard.AssistantSafetyPolicy;
    /** Retain the model's reasoning summary on assistant replies. Turning this off stops future capture; it does not erase reasoning already stored. */
    reasoning_capture?: boolean;
    /** Consent to the organization's assistant conversations being used as evaluation fixtures. Prospective-only: granting flags conversations started from now on; withdrawing stops flagging and excludes the organization from future fixture collection. Neither direction deletes or rewrites existing conversations. */
    eval_consent?: boolean;
}
