// This file was auto-generated by Fern from our API Definition.

/**
 * The lifecycle status transitions legal for an entire asset selection.
 */
export interface AllowedTransitions {
    /** Statuses every selected asset may move to next (the intersection of their legal-transition sets); empty if they share none. */
    allowed_transitions: AllowedTransitions.AllowedTransitions.Item[];
    object: AllowedTransitions.Object_;
}

export namespace AllowedTransitions {
    export type AllowedTransitions = AllowedTransitions.Item[];

    export namespace AllowedTransitions {
        /** A legal next status. */
        export const Item = {
            Active: "active",
            Maintenance: "maintenance",
            OutOfService: "out_of_service",
            Retired: "retired",
            Sold: "sold",
            Inactive: "inactive",
            Lost: "lost",
        } as const;
        export type Item = (typeof Item)[keyof typeof Item];
    }

    export const Object_ = {
        AllowedTransitions: "allowed_transitions",
    } as const;
    export type Object_ = (typeof Object_)[keyof typeof Object_];
}
