// This file was auto-generated by Fern from our API Definition.

/**
 * Time-bound binding between an asset and an operator in a role.
 */
export interface Assignment {
    /** Stable UUID. */
    id: string;
    /** Asset id. */
    asset_id: string;
    /** Operator id. */
    operator_id: string;
    /** Role discriminator for concurrent assignments on the same asset. */
    role: Assignment.Role;
    /** Start of validity. */
    valid_from: string;
    /** End of validity (null = still active). */
    valid_until?: string | undefined;
    /** Why the assignment was closed (null while active). */
    terminated_reason?: Assignment.TerminatedReason | undefined;
    /** Object type discriminator. */
    object: Assignment.Object_;
}

export namespace Assignment {
    /** Role discriminator for concurrent assignments on the same asset. */
    export const Role = {
        Primary: "primary",
        CoOperator: "co_operator",
        SafetyMonitor: "safety_monitor",
        RemotePilot: "remote_pilot",
        Supervisor: "supervisor",
    } as const;
    export type Role = (typeof Role)[keyof typeof Role];
    /** Why the assignment was closed (null while active). */
    export const TerminatedReason = {
        ShiftEnd: "shift_end",
        AssetMaintenance: "asset_maintenance",
        OperatorOffDuty: "operator_off_duty",
        Incident: "incident",
        SoftwareUpdate: "software_update",
        Reassigned: "reassigned",
        ContractEnded: "contract_ended",
        ManualClose: "manual_close",
    } as const;
    export type TerminatedReason = (typeof TerminatedReason)[keyof typeof TerminatedReason];
    /** Object type discriminator. */
    export const Object_ = {
        Assignment: "assignment",
    } as const;
    export type Object_ = (typeof Object_)[keyof typeof Object_];
}
