// This file was auto-generated by Fern from our API Definition.

import type * as NizamCarrier from "../index.js";

/**
 * Where the conversation matched. The `matched_in` discriminator selects the variant.
 */
export type AssistantSearchMatch =
    | NizamCarrier.AssistantSearchMatch.Title
    | NizamCarrier.AssistantSearchMatch.Artifact
    | NizamCarrier.AssistantSearchMatch.Message;

export namespace AssistantSearchMatch {
    export interface Title extends NizamCarrier.AssistantTitleMatch {
        matched_in: "title";
    }

    export interface Artifact extends NizamCarrier.AssistantArtifactMatch {
        matched_in: "artifact";
    }

    export interface Message extends NizamCarrier.AssistantMessageMatch {
        matched_in: "message";
    }
}
