// This file was auto-generated by Fern from our API Definition.

/**
 * Acknowledgement of a bulk admin action that fanned out one job per work item.
 */
export interface BulkJobSubmission {
    job_ids: string[];
    /** Number of jobs created (one per matched service account). */
    count: number;
    object: BulkJobSubmission.Object_;
}

export namespace BulkJobSubmission {
    export const Object_ = {
        BulkJobSubmission: "bulk_job_submission",
    } as const;
    export type Object_ = (typeof Object_)[keyof typeof Object_];
}
