// This file was auto-generated by Fern from our API Definition.

/**
 * An assistant conversation.
 */
export interface Conversation {
    /** Conversation id. */
    id: string;
    /** The member who owns the conversation. */
    owner_id: string;
    /** Title, or null if untitled. */
    title?: string | undefined;
    /** Who else in the org may read it. */
    visibility: Conversation.Visibility;
    /** Lifecycle status. */
    status: Conversation.Status;
    /** The selected persona (agent profile) the conversation converses as, or null to follow the organization's default persona. */
    agent_profile_id?: string | undefined;
    /** Creation timestamp. */
    created_at: string;
    /** Last-updated timestamp. */
    updated_at: string;
    /** Statuses this conversation may move to next — the wire projection of the transition matrix, derived from `status`. */
    allowed_transitions: Conversation.AllowedTransitions.Item[];
    /** Object type discriminator. */
    object: Conversation.Object_;
}

export namespace Conversation {
    /** Who else in the org may read it. */
    export const Visibility = {
        Private: "private",
        Workspace: "workspace",
        Org: "org",
    } as const;
    export type Visibility = (typeof Visibility)[keyof typeof Visibility];
    /** Lifecycle status. */
    export const Status = {
        Active: "active",
        Archived: "archived",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
    export type AllowedTransitions = AllowedTransitions.Item[];

    export namespace AllowedTransitions {
        /** A legal next status. */
        export const Item = {
            Active: "active",
            Archived: "archived",
        } as const;
        export type Item = (typeof Item)[keyof typeof Item];
    }

    /** Object type discriminator. */
    export const Object_ = {
        Conversation: "conversation",
    } as const;
    export type Object_ = (typeof Object_)[keyof typeof Object_];
}
