// This file was auto-generated by Fern from our API Definition.

/**
 * Initiates a bulk import: the import kind plus the source file's upload declaration. Returns a job handle and a presigned upload session.
 */
export interface CreateImportRequest {
    /** The import kind to run (lowercase). */
    kind: string;
    /** Original filename of the source file. */
    filename: string;
    /** Declared MIME type (must be allowed for import sources). */
    content_type: string;
    /** Declared byte size of the file. */
    size_bytes?: number | undefined;
    /** Client-computed SHA-256 of the file, 64 lowercase hex characters. */
    checksum_sha256?: string | undefined;
}
