// This file was auto-generated by Fern from our API Definition.

/**
 * Create a new task.
 */
export interface CreateTaskRequest {
    /** The kind of stop. */
    type: CreateTaskRequest.Type;
    /** Executor organization to delegate the task to (cross-org). Optional. */
    executor_organization_id?: string | undefined;
    /** Merchant the task belongs to. Optional. */
    merchant_id?: string | undefined;
    /** Free-form notes. */
    notes?: string | undefined;
}

export namespace CreateTaskRequest {
    /** The kind of stop. */
    export const Type = {
        Pickup: "pickup",
        Dropoff: "dropoff",
        Service: "service",
        Return: "return",
        Exchange: "exchange",
        EndAtHub: "end_at_hub",
        EndAtDriverAddress: "end_at_driver_address",
        RouteLoad: "route_load",
        Break: "break",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
