// This file was auto-generated by Fern from our API Definition.

/**
 * Mint a revocable link to a conversation.
 */
export interface CreateConversationShareRequest {
    /** How far the link reaches. `workspace` (the default) does not resolve for anonymous callers; `public` does, and is an explicit opt-in. */
    audience?: string | undefined;
    /** When the link should stop working. Omit for no expiry. */
    expires_at?: string | undefined;
}
