// This file was auto-generated by Fern from our API Definition.

/**
 * Names the organization the addressed subject-access request belongs to.
 */
export interface DsarRequestOrganization {
    /** The organization the request belongs to. */
    organization_id: string;
}
