// This file was auto-generated by Fern from our API Definition.

/**
 * Acknowledgement that an embedding backfill was enqueued.
 */
export interface EmbeddingBackfill {
    /** Id of the enqueued BACKFILL_EMBEDDINGS orchestrator job; poll it to observe progress as it fans out the per-subject embedding jobs. */
    job_id: string;
    object: EmbeddingBackfill.Object_;
}

export namespace EmbeddingBackfill {
    export const Object_ = {
        EmbeddingBackfill: "embedding_backfill",
    } as const;
    export type Object_ = (typeof Object_)[keyof typeof Object_];
}
