// This file was auto-generated by Fern from our API Definition.

/**
 * One file attached to a user message, in display order.
 */
export interface MessageAttachment {
    /** The attached file's id — mint a download URL via POST /v1/files/{id}/download-url. */
    file_id?: string | undefined;
    /** What the assistant treats the bytes as. */
    kind?: MessageAttachment.Kind | undefined;
    /** The uploaded file's original name. */
    filename?: string | undefined;
    /** The file's effective MIME type. */
    content_type?: string | undefined;
    /** The file's size in bytes. */
    size_bytes?: number | undefined;
    /** Whether the file's bytes are currently servable (malware scan cleared, not quarantined or deleted). */
    downloadable?: boolean | undefined;
}

export namespace MessageAttachment {
    /** What the assistant treats the bytes as. */
    export const Kind = {
        Image: "image",
        Pdf: "pdf",
        Document: "document",
        File: "file",
    } as const;
    export type Kind = (typeof Kind)[keyof typeof Kind];
}
