// This file was auto-generated by Fern from our API Definition.

import type * as NizamCarrier from "../index.js";

/**
 * A user's explicit per-kind × channel override.
 */
export interface NotificationPreference {
    /** Notification kind (wire key). */
    kind?: string | undefined;
    /** Delivery channel. */
    channel?: string | undefined;
    /** Whether the kind is enabled on this channel. */
    enabled?: boolean | undefined;
    quiet_hours?: NizamCarrier.QuietHours | undefined;
}
