// This file was auto-generated by Fern from our API Definition.

/**
 * Open a new assignment.
 */
export interface OpenAssignmentRequest {
    /** Asset id. */
    asset_id: string;
    /** Operator id. */
    operator_id: string;
    /** Role discriminator. */
    role: OpenAssignmentRequest.Role;
}

export namespace OpenAssignmentRequest {
    /** Role discriminator. */
    export const Role = {
        Primary: "primary",
        CoOperator: "co_operator",
        SafetyMonitor: "safety_monitor",
        RemotePilot: "remote_pilot",
        Supervisor: "supervisor",
    } as const;
    export type Role = (typeof Role)[keyof typeof Role];
}
