// This file was auto-generated by Fern from our API Definition.

/**
 * An asset as seen by an operator assigned to operate it, the operational identity fields, without the dashboard's lifecycle-management hints.
 */
export interface OperatorAsset {
    /** Stable UUID. */
    id: string;
    /** Top-level kind. */
    kind: OperatorAsset.Kind;
    /** Sub-kind within the kind (free-form). */
    sub_kind?: string | undefined;
    /** SAE J3016 autonomy level 0..5. */
    autonomy_level?: number | undefined;
    /** Lifecycle status. */
    status: OperatorAsset.Status;
    /** Display name. */
    name?: string | undefined;
    /** Vehicle Identification Number. */
    vin?: string | undefined;
    /** License plate. */
    plate_number?: string | undefined;
    /** Manufacturer. */
    make?: string | undefined;
    /** Model designation. */
    model?: string | undefined;
    /** Model year. */
    year?: number | undefined;
    /** Owning organization id. */
    organization_id?: string | undefined;
    /** Current primary operator (active assignment, role=primary). */
    current_primary_operator_id?: string | undefined;
    /** Object type discriminator. */
    object: OperatorAsset.Object_;
}

export namespace OperatorAsset {
    /** Top-level kind. */
    export const Kind = {
        GroundVehicle: "ground_vehicle",
        AerialVehicle: "aerial_vehicle",
        MarineVehicle: "marine_vehicle",
        Robot: "robot",
        Agv: "agv",
        Trailer: "trailer",
        Container: "container",
        Pallet: "pallet",
        Equipment: "equipment",
    } as const;
    export type Kind = (typeof Kind)[keyof typeof Kind];
    /** Lifecycle status. */
    export const Status = {
        Active: "active",
        Maintenance: "maintenance",
        OutOfService: "out_of_service",
        Retired: "retired",
        Sold: "sold",
        Inactive: "inactive",
        Lost: "lost",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
    /** Object type discriminator. */
    export const Object_ = {
        Asset: "asset",
    } as const;
    export type Object_ = (typeof Object_)[keyof typeof Object_];
}
