// This file was auto-generated by Fern from our API Definition.

import type * as NizamCarrier from "../index.js";

/**
 * A publicly sellable subscription plan, for the pricing page.
 */
export interface PricingPlan {
    /** Stable plan code. */
    code: string;
    /** Display name. */
    name: string;
    /** Marketing description. */
    description?: string | undefined;
    price: NizamCarrier.Money;
    setup_fee: NizamCarrier.Money;
    machine_price: NizamCarrier.Money;
    /** Pricing shape. */
    billing_model: PricingPlan.BillingModel;
    /** Billing cadence. */
    billing_period: PricingPlan.BillingPeriod;
    /** Free-trial length in days, when the plan offers one. */
    trial_days?: number | undefined;
    features: NizamCarrier.PlanFeatures;
    object: PricingPlan.Object_;
}

export namespace PricingPlan {
    /** Pricing shape. */
    export const BillingModel = {
        Free: "free",
        Flat: "flat",
        PerSeat: "per_seat",
        PerEvent: "per_event",
        Tiered: "tiered",
        Hybrid: "hybrid",
    } as const;
    export type BillingModel = (typeof BillingModel)[keyof typeof BillingModel];
    /** Billing cadence. */
    export const BillingPeriod = {
        Weekly: "weekly",
        Biweekly: "biweekly",
        Monthly: "monthly",
        Quarterly: "quarterly",
        Semiannual: "semiannual",
        Yearly: "yearly",
    } as const;
    export type BillingPeriod = (typeof BillingPeriod)[keyof typeof BillingPeriod];
    export const Object_ = {
        PricingPlan: "pricing_plan",
    } as const;
    export type Object_ = (typeof Object_)[keyof typeof Object_];
}
