// This file was auto-generated by Fern from our API Definition.

/**
 * Match a COD collection into a merchant payout.
 */
export interface ReconcileCodCollectionRequest {
    /** The merchant payout to reconcile this collection into. */
    merchant_payout_id: string;
}
