// This file was auto-generated by Fern from our API Definition.

/**
 * File a conversation into a project.
 */
export interface SelectConversationProjectRequest {
    /** The project to file into. Must be owned by the caller. */
    project_id: string;
}
