// This file was auto-generated by Fern from our API Definition.

import type * as NizamCarrier from "../index.js";

/**
 * A started subscription and the checkout URL to complete it.
 */
export interface SubscriptionCheckout {
    subscription: NizamCarrier.PlatformSubscription;
    /** Hosted checkout URL to complete payment; null when billing is disabled. */
    checkout_url?: string | undefined;
    object: SubscriptionCheckout.Object_;
}

export namespace SubscriptionCheckout {
    export const Object_ = {
        SubscriptionCheckout: "subscription_checkout",
    } as const;
    export type Object_ = (typeof Object_)[keyof typeof Object_];
}
