// This file was auto-generated by Fern from our API Definition.

/**
 * Set-only partial update of a collection's name and description. Omitted or null fields are left unchanged.
 */
export interface UpdateKnowledgeCollectionRequest {
    /** New name. Omit to leave unchanged. */
    name?: string | undefined;
    /** New description. Omit to leave unchanged. */
    description?: string | undefined;
}
