// This file was auto-generated by Fern from our API Definition.

/**
 * Update a task (set-only partial update).
 */
export interface UpdateTaskRequest {
    /** Free-form notes. */
    notes?: string | undefined;
}
