// This file was auto-generated by Fern from our API Definition.

import type * as NizamDashboard from "../../../../index.js";

/**
 * @example
 *     {
 *         id: "00000000-0000-0000-0000-000000000000"
 *     }
 */
export interface GetKnowledgeDocumentRequest {
    id: string;
    /** Inline related resources instead of returning id-only references. Allowed: `collection`. Repeat the parameter (`expand[]=a&expand[]=b`) to inline several; dot-notation chains a nested hop (max depth 4). An unknown or unpermitted value is rejected with `400 validation_failed`. Unexpanded relations stay id-only and the nested object is omitted from the response. */
    "expand[]"?:
        | NizamDashboard.GetKnowledgeDocumentRequestExpandItem
        | NizamDashboard.GetKnowledgeDocumentRequestExpandItem[];
}
