// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "00000000-0000-0000-0000-000000000000",
 *         title: "Employee Handbook 2026 (rev B)",
 *         collection_id: "a2b3c4d5-6e7f-4809-9a0b-1c2d3e4f5a6b",
 *         metadata: {
 *             "department": {
 *                 "key": "value"
 *             }
 *         }
 *     }
 */
export interface UpdateKnowledgeDocumentRequest {
    id: string;
    /** New title. Omit to leave unchanged. */
    title?: string;
    /** Move the document into this collection. Omit to leave unchanged. */
    collection_id?: string;
    /** Replace the free-form metadata wholesale. Omit to leave unchanged. */
    metadata?: Record<string, Record<string, unknown>>;
}
