// This file was auto-generated by Fern from our API Definition.

export const ListAssetsRequestMode = {
    Text: "text",
    Semantic: "semantic",
} as const;
export type ListAssetsRequestMode = (typeof ListAssetsRequestMode)[keyof typeof ListAssetsRequestMode];
