// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         slug: "acme-logistics"
 *     }
 *
 * @example
 *     {
 *         slug: "globex-freight"
 *     }
 */
export interface SetActiveOrganizationRequest {
    /** Slug of the organization to make active. Must match an active membership. */
    slug: string;
}
