// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         "Idempotency-Key": "9f1e6d2a-7c3b-4e5f-8a91-0b2c3d4e5f60",
 *         kind: "profile_picture",
 *         subject_type: "task_attempt",
 *         subject_id: "b3c4d5e6-7f8a-9b0c-1d2e-3f4a5b6c7d8e",
 *         filename: "pod-photo.jpg",
 *         content_type: "image/jpeg",
 *         size_bytes: 2048576,
 *         checksum_sha256: "9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08"
 *     }
 */
export interface InitiateFileUploadRequest {
    /** Optional. Supply a UUID (canonical 8-4-4-4-12 form; lowercase v4 recommended) to make this operation idempotent: the same key on a retry replays the original outcome instead of creating a second resource. 2xx successes and deliberate 4xx domain rejections are cached and replayed for 24h when the request body matches; transient 5xx responses are never cached, so a retry with the same key re-executes. A malformed key is rejected with 400 `idempotency.invalid_key`; reusing a key with a different request body is 409 `idempotency.key_conflict`; a key still in flight is 409 `idempotency.in_progress`. Omit the header and the operation behaves like any other write. */
    "Idempotency-Key"?: string;
    /** What the bytes are for the platform — fixes the policy applied to them. */
    kind: InitiateFileUploadRequest.Kind;
    /** Type of the business entity this file documents (optional at upload time; can also be attached later). */
    subject_type?: string;
    /** Id of the business entity this file documents. Requires subject_type. */
    subject_id?: string;
    /** Original filename; served back via Content-Disposition on download. */
    filename: string;
    /** Declared MIME type. Must be on the kind's allow-list; re-verified by server-side detection at completion. */
    content_type: string;
    /** Exact byte size of the file. Verified against storage at completion. */
    size_bytes?: number;
    /** SHA-256 of the content as 64 lowercase hex characters (compute with crypto.subtle.digest). Re-verified server-side by the scan pipeline. */
    checksum_sha256: string;
}

export namespace InitiateFileUploadRequest {
    /** What the bytes are for the platform — fixes the policy applied to them. */
    export const Kind = {
        ProfilePicture: "profile_picture",
        ChatAttachment: "chat_attachment",
        TaskPodPhoto: "task_pod_photo",
        ImportSource: "import_source",
        ImportReport: "import_report",
        SignedDocument: "signed_document",
        ProductImage: "product_image",
        DataExport: "data_export",
    } as const;
    export type Kind = (typeof Kind)[keyof typeof Kind];
}
