// This file was auto-generated by Fern from our API Definition.

export const ListKnowledgeDocumentsRequestSortItem = {
    CreatedAtAsc: "created_at:asc",
    CreatedAtDesc: "created_at:desc",
    UpdatedAtAsc: "updated_at:asc",
    UpdatedAtDesc: "updated_at:desc",
    TitleAsc: "title:asc",
    TitleDesc: "title:desc",
    CollectionAsc: "collection:asc",
    CollectionDesc: "collection:desc",
    StatusAsc: "status:asc",
    StatusDesc: "status:desc",
    SourceAsc: "source:asc",
    SourceDesc: "source:desc",
    SizeAsc: "size:asc",
    SizeDesc: "size:desc",
} as const;
export type ListKnowledgeDocumentsRequestSortItem =
    (typeof ListKnowledgeDocumentsRequestSortItem)[keyof typeof ListKnowledgeDocumentsRequestSortItem];
