// This file was auto-generated by Fern from our API Definition.

export const ListKnowledgeDocumentsRequestStatusItem = {
    Pending: "pending",
    Extracting: "extracting",
    Chunking: "chunking",
    Indexed: "indexed",
    Failed: "failed",
    Archived: "archived",
} as const;
export type ListKnowledgeDocumentsRequestStatusItem =
    (typeof ListKnowledgeDocumentsRequestStatusItem)[keyof typeof ListKnowledgeDocumentsRequestStatusItem];
