// This file was auto-generated by Fern from our API Definition.

export const ListAllArtifactsRequestTypeItem = {
    Document: "document",
    Code: "code",
    Diagram: "diagram",
} as const;
export type ListAllArtifactsRequestTypeItem =
    (typeof ListAllArtifactsRequestTypeItem)[keyof typeof ListAllArtifactsRequestTypeItem];
