// This file was auto-generated by Fern from our API Definition.

export const ListAllArtifactsRequestScope = {
    Owned: "owned",
    Shared: "shared",
} as const;
export type ListAllArtifactsRequestScope =
    (typeof ListAllArtifactsRequestScope)[keyof typeof ListAllArtifactsRequestScope];
