// This file was auto-generated by Fern from our API Definition.

/**
 * The autonomy envelope for an agent persona.
 */
export interface AgentAutonomyPolicyInput {
    /** Whether this persona may run autonomously at all. */
    autonomous_allowed?: boolean | undefined;
    /** Positive cap on steps per run; null for no cap. */
    max_steps?: number | undefined;
    /** Positive per-run token cap; null for no cap. */
    token_budget?: number | undefined;
    /** Positive per-run AI-credit cap; null for no cap. */
    credit_budget?: number | undefined;
    /** Whether tool calls need human approval; defaults to manual. */
    tool_approval_mode?: AgentAutonomyPolicyInput.ToolApprovalMode | undefined;
    /** Allowed run triggers; empty when not autonomous. */
    allowed_triggers?: AgentAutonomyPolicyInput.AllowedTriggers.Item[] | undefined;
}

export namespace AgentAutonomyPolicyInput {
    /** Whether tool calls need human approval; defaults to manual. */
    export const ToolApprovalMode = {
        Auto: "auto",
        Manual: "manual",
    } as const;
    export type ToolApprovalMode = (typeof ToolApprovalMode)[keyof typeof ToolApprovalMode];
    export type AllowedTriggers = AllowedTriggers.Item[];

    export namespace AllowedTriggers {
        /** Allowed run triggers; empty when not autonomous. */
        export const Item = {
            Manual: "manual",
            Cron: "cron",
            Event: "event",
        } as const;
        export type Item = (typeof Item)[keyof typeof Item];
    }
}
