// This file was auto-generated by Fern from our API Definition.

/**
 * Something said in the conversation, on its current branch, matched.
 */
export interface AssistantMessageMatch {
    /** The message that matched — open the thread scrolled to it. */
    message_id?: string | undefined;
    /** Who said it. Never `system` — summaries are not searched. */
    role?: AssistantMessageMatch.Role | undefined;
}

export namespace AssistantMessageMatch {
    /** Who said it. Never `system` — summaries are not searched. */
    export const Role = {
        User: "user",
        Assistant: "assistant",
        System: "system",
        Tool: "tool",
    } as const;
    export type Role = (typeof Role)[keyof typeof Role];
}
