// This file was auto-generated by Fern from our API Definition.

/**
 * Self-selected vertical an organization operates in. Picker option for the onboarding flow.
 */
export interface BusinessCategory {
    /** Stable slug — matches the DB CHECK constraint on `organizations.business_category`. */
    slug: string;
    /** Human-readable label for picker UIs. */
    display_name: string;
    /** Object type discriminator. */
    object: BusinessCategory.Object_;
}

export namespace BusinessCategory {
    /** Object type discriminator. */
    export const Object_ = {
        BusinessCategory: "business_category",
    } as const;
    export type Object_ = (typeof Object_)[keyof typeof Object_];
}
