// This file was auto-generated by Fern from our API Definition.

/**
 * Run one AI review over the artifact's current version. Charges AI credits.
 */
export interface GenerateSuggestionsRequest {
    /** What to focus on — omit for a general review. */
    instruction?: string | undefined;
}
