// This file was auto-generated by Fern from our API Definition.

import type * as NizamCustomer from "../index.js";

/**
 * A merchant payout: the merchant, settlement period, money rollups, lifecycle status and destination.
 */
export interface MerchantPayout {
    /** Unique identifier of the payout. */
    id: string;
    /** The merchant being settled. */
    merchant_id: string;
    /** Start of the settlement period. */
    period_start?: string | undefined;
    /** End of the settlement period. */
    period_end?: string | undefined;
    /** Settlement lifecycle status. */
    status: MerchantPayout.Status;
    gross: NizamCustomer.Money;
    fees: NizamCustomer.Money;
    net: NizamCustomer.Money;
    /** The disbursement rail. */
    payment_method: MerchantPayout.PaymentMethod;
    /** The frozen destination kind, once recorded. */
    payment_destination_type?: MerchantPayout.PaymentDestinationType | undefined;
    /** Destination bank name (snapshot). */
    bank_name?: string | undefined;
    /** Destination account holder name (snapshot). */
    bank_account_name?: string | undefined;
    /** Last 4 digits of the destination account (PCI-aware). */
    bank_account_last4?: string | undefined;
    /** Last 4 digits of the destination routing number (PCI-aware). */
    bank_routing_last4?: string | undefined;
    /** Cheque number, for a cheque disbursement. */
    cheque_number?: string | undefined;
    /** The processor transfer reference, once disbursed. */
    processor_transfer_id?: string | undefined;
    /** An external reference for the disbursement. */
    external_reference?: string | undefined;
    /** When the payout is scheduled to run. */
    scheduled_for?: string | undefined;
    /** When the payout was disbursed. */
    sent_at?: string | undefined;
    /** When the payout failed. */
    failed_at?: string | undefined;
    /** Why the payout failed. */
    failure_reason?: string | undefined;
    /** Free-form settlement note. */
    notes?: string | undefined;
    /** The lifecycle statuses this payout may legally move to next. */
    allowed_transitions: MerchantPayout.AllowedTransitions.Item[];
    /** When the payout was created. */
    created_at: string;
    /** The settlement lines (detail read only). */
    lines?: NizamCustomer.MerchantPayoutLine[] | undefined;
    object: MerchantPayout.Object_;
}

export namespace MerchantPayout {
    /** Settlement lifecycle status. */
    export const Status = {
        Draft: "draft",
        Pending: "pending",
        OnHold: "on_hold",
        Scheduled: "scheduled",
        Processing: "processing",
        Sent: "sent",
        Failed: "failed",
        Reversed: "reversed",
        Canceled: "canceled",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
    /** The disbursement rail. */
    export const PaymentMethod = {
        Wire: "wire",
        Ach: "ach",
        Cheque: "cheque",
        ProcessorTransfer: "processor_transfer",
        Card: "card",
        Paypal: "paypal",
        DigitalWallet: "digital_wallet",
        Cash: "cash",
        InternalCredit: "internal_credit",
        Adjustment: "adjustment",
    } as const;
    export type PaymentMethod = (typeof PaymentMethod)[keyof typeof PaymentMethod];
    /** The frozen destination kind, once recorded. */
    export const PaymentDestinationType = {
        BankAccount: "bank_account",
        ConnectedAccount: "connected_account",
        ChequeMail: "cheque_mail",
        Card: "card",
        Paypal: "paypal",
        DigitalWallet: "digital_wallet",
        InternalBalance: "internal_balance",
        Cash: "cash",
    } as const;
    export type PaymentDestinationType = (typeof PaymentDestinationType)[keyof typeof PaymentDestinationType];
    export type AllowedTransitions = AllowedTransitions.Item[];

    export namespace AllowedTransitions {
        export const Item = {
            Draft: "draft",
            Pending: "pending",
            OnHold: "on_hold",
            Scheduled: "scheduled",
            Processing: "processing",
            Sent: "sent",
            Failed: "failed",
            Reversed: "reversed",
            Canceled: "canceled",
        } as const;
        export type Item = (typeof Item)[keyof typeof Item];
    }

    export const Object_ = {
        MerchantPayout: "merchant_payout",
    } as const;
    export type Object_ = (typeof Object_)[keyof typeof Object_];
}
