// This file was auto-generated by Fern from our API Definition.

/**
 * The current position of one operator.
 */
export interface OperatorPosition {
    /** Operator id. */
    operator_id?: string | undefined;
    /** Latitude (WGS84). */
    lat?: number | undefined;
    /** Longitude (WGS84). */
    lng?: number | undefined;
    /** Direction of travel, compass degrees [0,360). */
    heading?: number | undefined;
    /** Course over ground, compass degrees [0,360). */
    bearing?: number | undefined;
    /** Ground speed, km/h. */
    speed?: number | undefined;
    /** Altitude above the WGS84 ellipsoid, metres. */
    altitude?: number | undefined;
    /** Device-time of the fix. */
    captured_at?: string | undefined;
    object?: OperatorPosition.Object_ | undefined;
}

export namespace OperatorPosition {
    export const Object_ = {
        OperatorPosition: "operator_position",
    } as const;
    export type Object_ = (typeof Object_)[keyof typeof Object_];
}
