// This file was auto-generated by Fern from our API Definition.

import type * as NizamCustomer from "../index.js";

/**
 * Place a preservation order over a data subject or a single conversation.
 */
export interface PlaceLegalHoldRequest {
    /** The organization whose data is preserved. */
    organization_id: string;
    target: NizamCustomer.LegalHoldTarget;
    /** Why the hold is being placed. Recorded verbatim and surfaced to whoever later considers lifting it. */
    reason: string;
}
