// This file was auto-generated by Fern from our API Definition.

/**
 * A short-lived ticket authorizing a single realtime (STOMP/WebSocket) connection.
 */
export interface RealtimeTicket {
    /** The signed ticket. Send it as `Authorization: Bearer <ticket>` on the STOMP CONNECT frame to /ws. Opaque to the client; do not parse or store it. */
    ticket?: string | undefined;
    /** When the ticket expires (ISO-8601). Connect promptly; mint a fresh ticket for each new connection attempt. */
    expires_at?: string | undefined;
    /** Object type discriminator (Stripe pattern). */
    object?: RealtimeTicket.Object_ | undefined;
}

export namespace RealtimeTicket {
    /** Object type discriminator (Stripe pattern). */
    export const Object_ = {
        RealtimeTicket: "realtime_ticket",
    } as const;
    export type Object_ = (typeof Object_)[keyof typeof Object_];
}
