// This file was auto-generated by Fern from our API Definition.

import type * as NizamCustomer from "../index.js";

/**
 * Protocol configuration derived from the provider's published metadata.
 */
export type SsoConnectionConfiguration =
    | NizamCustomer.SsoConnectionConfiguration.Oidc
    | NizamCustomer.SsoConnectionConfiguration.Saml;

export namespace SsoConnectionConfiguration {
    export interface Oidc extends NizamCustomer.SsoOidcConfiguration {
        protocol: "oidc";
    }

    export interface Saml extends NizamCustomer.SsoSamlConfiguration {
        protocol: "saml";
    }
}
