// This file was auto-generated by Fern from our API Definition.

/**
 * Per-surface safety actions and the semantic-judge opt-in.
 */
export interface AssistantSafetyPolicy {
    /** Action when the member's submitted text trips a safety detection. */
    input?: AssistantSafetyPolicy.Input | undefined;
    /** Action when the assistant's generated reply trips a safety detection. */
    output?: AssistantSafetyPolicy.Output | undefined;
    /** Action when a retrieved knowledge chunk trips a safety detection. */
    rag?: AssistantSafetyPolicy.Rag | undefined;
    /** Action when a tool result trips a safety detection. */
    tools?: AssistantSafetyPolicy.Tools | undefined;
    /** Action when an attached document's text trips a safety detection. */
    attachments?: AssistantSafetyPolicy.Attachments | undefined;
    /** Whether the semantic LLM judge screens surfaces on top of the deterministic layer. */
    judge?: boolean | undefined;
}

export namespace AssistantSafetyPolicy {
    /** Action when the member's submitted text trips a safety detection. */
    export const Input = {
        Block: "block",
        Flag: "flag",
    } as const;
    export type Input = (typeof Input)[keyof typeof Input];
    /** Action when the assistant's generated reply trips a safety detection. */
    export const Output = {
        Block: "block",
        Flag: "flag",
    } as const;
    export type Output = (typeof Output)[keyof typeof Output];
    /** Action when a retrieved knowledge chunk trips a safety detection. */
    export const Rag = {
        Block: "block",
        Flag: "flag",
    } as const;
    export type Rag = (typeof Rag)[keyof typeof Rag];
    /** Action when a tool result trips a safety detection. */
    export const Tools = {
        Block: "block",
        Flag: "flag",
    } as const;
    export type Tools = (typeof Tools)[keyof typeof Tools];
    /** Action when an attached document's text trips a safety detection. */
    export const Attachments = {
        Block: "block",
        Flag: "flag",
    } as const;
    export type Attachments = (typeof Attachments)[keyof typeof Attachments];
}
