// This file was auto-generated by Fern from our API Definition.

import type * as NizamMerchant from "../index.js";

/**
 * Where the conversation matched. The `matched_in` discriminator selects the variant.
 */
export type AssistantSearchMatch =
    | NizamMerchant.AssistantSearchMatch.Title
    | NizamMerchant.AssistantSearchMatch.Artifact
    | NizamMerchant.AssistantSearchMatch.Message;

export namespace AssistantSearchMatch {
    export interface Title extends NizamMerchant.AssistantTitleMatch {
        matched_in: "title";
    }

    export interface Artifact extends NizamMerchant.AssistantArtifactMatch {
        matched_in: "artifact";
    }

    export interface Message extends NizamMerchant.AssistantMessageMatch {
        matched_in: "message";
    }
}
