// This file was auto-generated by Fern from our API Definition.

/**
 * ISO 4217 currency with localized name + symbol.
 */
export interface Currency {
    /** ISO 4217 code. */
    code: string;
    /** Display name in the Accept-Language locale. */
    name: string;
    /** Short symbol in the Accept-Language locale. */
    symbol: string;
    /** Default number of fractional digits per ISO 4217. */
    fraction_digits: number;
    /** Object type discriminator. */
    object: Currency.Object_;
}

export namespace Currency {
    /** Object type discriminator. */
    export const Object_ = {
        Currency: "currency",
    } as const;
    export type Object_ = (typeof Object_)[keyof typeof Object_];
}
