// This file was auto-generated by Fern from our API Definition.

/**
 * Aggregated position count for one H3 hex cell.
 */
export interface HeatmapCell {
    /** H3 cell index, lowercase hex (string: H3 indexes exceed the JS safe-integer range). */
    h3_cell: string;
    /** H3 resolution of the cell (9 or 11). */
    h3_res: number;
    /** Number of positions recorded in the cell over the window. */
    count: number;
    object: HeatmapCell.Object_;
}

export namespace HeatmapCell {
    export const Object_ = {
        HeatmapCell: "heatmap_cell",
    } as const;
    export type Object_ = (typeof Object_)[keyof typeof Object_];
}
