// This file was auto-generated by Fern from our API Definition.

import type * as NizamMerchant from "../index.js";

/**
 * A single line item of an invoice: its source, quantity and money rollups.
 */
export interface InvoiceItem {
    /** Unique identifier of the line item. */
    id: string;
    /** The billable-origin kind, or null for an ad-hoc charge line. */
    source_type?: string | undefined;
    /** The originating entity id, when the line is entity-backed. */
    source_id?: string | undefined;
    /** Human-readable line description. */
    description?: string | undefined;
    /** Optional billing code. */
    code?: string | undefined;
    /** Billed quantity (fractional). */
    quantity: string;
    unit_amount: NizamMerchant.Money;
    subtotal: NizamMerchant.Money;
    discount: NizamMerchant.Money;
    tax: NizamMerchant.Money;
    amount_total: NizamMerchant.Money;
    object: InvoiceItem.Object_;
}

export namespace InvoiceItem {
    export const Object_ = {
        InvoiceItem: "invoice_item",
    } as const;
    export type Object_ = (typeof Object_)[keyof typeof Object_];
}
