// This file was auto-generated by Fern from our API Definition.

import type * as NizamMerchant from "../index.js";

/**
 * A document in a knowledge base: its metadata and ingestion status. Content is extracted, chunked, and embedded so it can ground retrieval-augmented answers.
 */
export interface KnowledgeDocument {
    /** Stable UUID. */
    id: string;
    /** The collection this document is filed under, or null if ungrouped. */
    collection_id?: string | undefined;
    collection?: NizamMerchant.KnowledgeCollectionSummary | undefined;
    /** Display title. */
    title: string;
    /** How the content was supplied. */
    source: KnowledgeDocument.Source;
    /** Detected MIME type of the source content. */
    content_type?: string | undefined;
    /** Ingestion lifecycle status. */
    status: KnowledgeDocument.Status;
    /** Why extraction or indexing failed; present only when status is `failed`. */
    failure_reason?: string | undefined;
    /** Number of embedded chunks (0 until indexed). */
    chunk_count: number;
    /** The bound source file, or null before an upload completes. */
    source_file_id?: string | undefined;
    /** Source file size in bytes, present on list projections; null on the single-document read and before an upload binds a file. */
    size?: number | undefined;
    /** Free-form metadata. Returned on the single-document read; omitted from list projections. */
    metadata?: Record<string, Record<string, unknown>> | undefined;
    /** When the document was registered. */
    created_at: string;
    /** When the document was last modified. */
    updated_at: string;
    /** Object type discriminator. */
    object: KnowledgeDocument.Object_;
}

export namespace KnowledgeDocument {
    /** How the content was supplied. */
    export const Source = {
        Upload: "upload",
        Url: "url",
        Inline: "inline",
        Connector: "connector",
    } as const;
    export type Source = (typeof Source)[keyof typeof Source];
    /** Ingestion lifecycle status. */
    export const Status = {
        Pending: "pending",
        Extracting: "extracting",
        Chunking: "chunking",
        Indexed: "indexed",
        Failed: "failed",
        Archived: "archived",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
    /** Object type discriminator. */
    export const Object_ = {
        KnowledgeDocument: "knowledge_document",
    } as const;
    export type Object_ = (typeof Object_)[keyof typeof Object_];
}
