// This file was auto-generated by Fern from our API Definition.

import type * as NizamMerchant from "../index.js";

/**
 * What the hold preserves. The scope discriminator selects the variant.
 */
export type LegalHoldTarget = NizamMerchant.LegalHoldTarget.Subject | NizamMerchant.LegalHoldTarget.Conversation;

export namespace LegalHoldTarget {
    export interface Subject extends NizamMerchant.LegalHoldSubjectTarget {
        scope: "subject";
    }

    export interface Conversation extends NizamMerchant.LegalHoldConversationTarget {
        scope: "conversation";
    }
}
