// This file was auto-generated by Fern from our API Definition.

import type * as NizamMerchant from "../index.js";

/**
 * An organization's legal holds, newest first.
 */
export interface LegalHoldList {
    /** The organization's holds, newest first. */
    legal_holds: NizamMerchant.LegalHold[];
    object: LegalHoldList.Object_;
}

export namespace LegalHoldList {
    export const Object_ = {
        AssistantLegalHoldList: "assistant_legal_hold_list",
    } as const;
    export type Object_ = (typeof Object_)[keyof typeof Object_];
}
