// This file was auto-generated by Fern from our API Definition.

/**
 * A monetary amount as integer minor units plus its ISO-4217 currency.
 */
export interface Money {
    /** ISO-4217 currency code. */
    currency: string;
    /** Amount in the currency's minor units (cents for USD, yen for JPY, fils for KWD). */
    minor_units: number;
    /** Amount as a major-unit decimal string at the currency's scale. */
    decimal: string;
}
