// This file was auto-generated by Fern from our API Definition.

import type * as NizamMerchant from "../index.js";

/**
 * A proof-of-delivery photo captured during a task attempt.
 */
export interface TaskAttemptPhoto {
    /** Photo record id. */
    id: string;
    /** Central file id: request bytes via the files download-url endpoint. */
    file_id: string;
    /** Display order within the attempt. */
    sequence: number;
    /** Photo category, when categorised. */
    photo_type?: string | undefined;
    /** Operator-entered caption. */
    caption?: string | undefined;
    /** Device capture time (EXIF), when reported. */
    taken_at?: string | undefined;
    /** May the bytes be served right now (scan verdict + lifecycle)? */
    downloadable: boolean;
    thumbnails: NizamMerchant.TaskAttemptPhotoThumbnail[];
    /** When the photo row was recorded. */
    created_at: string;
    object: TaskAttemptPhoto.Object_;
}

export namespace TaskAttemptPhoto {
    export const Object_ = {
        TaskAttemptPhoto: "task_attempt_photo",
    } as const;
    export type Object_ = (typeof Object_)[keyof typeof Object_];
}
