// This file was auto-generated by Fern from our API Definition.

import type * as NizamMerchant from "../index.js";

/**
 * The sign-in methods registered on the current user's account.
 */
export interface UserCredentials {
    /** Every registered sign-in method, including the password. Empty is impossible in practice — an account that can authenticate has at least one credential — but is not an error. */
    credentials: NizamMerchant.RegisteredCredential[];
    object: UserCredentials.Object_;
}

export namespace UserCredentials {
    export const Object_ = {
        UserCredentials: "user_credentials",
    } as const;
    export type Object_ = (typeof Object_)[keyof typeof Object_];
}
