// This file was auto-generated by Fern from our API Definition.

import type * as NizamCustomer from "../../../../index.js";

/**
 * @example
 *     {
 *         preferences: [{}]
 *     }
 */
export interface UpdateNotificationPreferences {
    /** The overrides to apply; each fully declares one (kind, channel). */
    preferences?: NizamCustomer.NotificationPreferenceItem[];
}
