// This file was auto-generated by Fern from our API Definition.

import type * as NizamDashboard from "../../../../index.js";

/**
 * @example
 *     {
 *         "Idempotency-Key": "9f1e6d2a-7c3b-4e5f-8a91-0b2c3d4e5f60",
 *         name: "Support \u2014 Tier 1",
 *         description: "Handles first-line delivery questions.",
 *         category: "customer_support",
 *         config: {
 *             model_settings: {
 *                 model: "gemini-3-flash-preview",
 *                 temperature: 0.2,
 *                 max_output_tokens: 1024
 *             },
 *             instructions: "Always confirm the delivery address before rescheduling.",
 *             tools: ["knowledge.search"],
 *             knowledge_collection_ids: ["3f2504e0-4f89-11d3-9a0c-0305e82c3301"],
 *             autonomy: {
 *                 autonomous_allowed: false,
 *                 max_steps: 20,
 *                 token_budget: 100000,
 *                 credit_budget: 50,
 *                 tool_approval_mode: "manual",
 *                 allowed_triggers: ["manual"]
 *             }
 *         }
 *     }
 */
export interface CreateAgentProfileRequest {
    /** Optional. Supply a UUID (canonical 8-4-4-4-12 form; lowercase v4 recommended) to make this operation idempotent: the same key on a retry replays the original outcome instead of creating a second resource. 2xx successes and deliberate 4xx domain rejections are cached and replayed for 24h when the request body matches; transient 5xx responses are never cached, so a retry with the same key re-executes. A malformed key is rejected with 400 `idempotency.invalid_key`; reusing a key with a different request body is 409 `idempotency.key_conflict`; a key still in flight is 409 `idempotency.in_progress`. Omit the header and the operation behaves like any other write. */
    "Idempotency-Key"?: string;
    /** Display name. */
    name: string;
    /** Optional description. */
    description?: string;
    /** Reserved category — selects the base prompt preset. */
    category: CreateAgentProfileRequest.Category;
    config?: NizamDashboard.AgentProfileConfigInput;
}

export namespace CreateAgentProfileRequest {
    /** Reserved category — selects the base prompt preset. */
    export const Category = {
        CustomerSupport: "customer_support",
        SalesOutreach: "sales_outreach",
        CallCenter: "call_center",
        Operations: "operations",
        General: "general",
    } as const;
    export type Category = (typeof Category)[keyof typeof Category];
}
