// This file was auto-generated by Fern from our API Definition.

export const ListOrgAddonsRequestSortItem = {
    CreatedAtAsc: "created_at:asc",
    CreatedAtDesc: "created_at:desc",
} as const;
export type ListOrgAddonsRequestSortItem =
    (typeof ListOrgAddonsRequestSortItem)[keyof typeof ListOrgAddonsRequestSortItem];
