// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         domain: "acme.com"
 *     }
 */
export interface ClaimDomainRequest {
    /** The domain to claim (bare domain, no scheme). */
    domain: string;
}
