// This file was auto-generated by Fern from our API Definition.

import { InvitesClient } from "./api/resources/invites/client/Client.js";
import { LookupsClient } from "./api/resources/lookups/client/Client.js";
import { PositionsClient } from "./api/resources/positions/client/Client.js";
import { RealtimeClient } from "./api/resources/realtime/client/Client.js";
import { UsersClient } from "./api/resources/users/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "./BaseClient.js";
import * as core from "./core/index.js";

export declare namespace NizamOperatorRuntimeClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class NizamOperatorRuntimeClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<NizamOperatorRuntimeClient.Options>;
    protected _invites: InvitesClient | undefined;
    protected _lookups: LookupsClient | undefined;
    protected _users: UsersClient | undefined;
    protected _positions: PositionsClient | undefined;
    protected _realtime: RealtimeClient | undefined;

    constructor(options: NizamOperatorRuntimeClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get invites(): InvitesClient {
        return (this._invites ??= new InvitesClient(this._options));
    }

    public get lookups(): LookupsClient {
        return (this._lookups ??= new LookupsClient(this._options));
    }

    public get users(): UsersClient {
        return (this._users ??= new UsersClient(this._options));
    }

    public get positions(): PositionsClient {
        return (this._positions ??= new PositionsClient(this._options));
    }

    public get realtime(): RealtimeClient {
        return (this._realtime ??= new RealtimeClient(this._options));
    }

    /**
     * Make a passthrough request using the SDK's configured auth, retry, logging, etc.
     * This is useful for making requests to endpoints not yet supported in the SDK.
     * The input can be a URL string, URL object, or Request object. Relative paths are resolved against the configured base URL.
     *
     * @param {Request | string | URL} input - The URL, path, or Request object.
     * @param {RequestInit} init - Standard fetch RequestInit options.
     * @param {core.PassthroughRequest.RequestOptions} requestOptions - Per-request overrides (timeout, retries, headers, abort signal).
     * @returns {Promise<Response>} A standard Response object.
     */
    public async fetch(
        input: Request | string | URL,
        init?: RequestInit,
        requestOptions?: core.PassthroughRequest.RequestOptions,
    ): Promise<Response> {
        return core.makePassthroughRequest(
            input,
            init,
            {
                baseUrl: this._options.baseUrl ?? this._options.environment,
                headers: this._options.headers,
                timeoutInSeconds: this._options.timeoutInSeconds,
                maxRetries: this._options.maxRetries,
                fetch: this._options.fetch,
                logging: this._options.logging,
                getAuthHeaders: async () => (await this._options.authProvider.getAuthRequest()).headers,
            },
            requestOptions,
        );
    }
}
