// This file was auto-generated by Fern from our API Definition.

export const NizamOperatorRuntimeEnvironment = {
    Production: "https://api.nizam.ai",
} as const;

export type NizamOperatorRuntimeEnvironment = typeof NizamOperatorRuntimeEnvironment.Production;
