// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface ListUsersRequest {
    limit?: number;
    offset?: number;
    /** Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
    sort?: string | string[];
}
