// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         q: "<string>",
 *         starting_after: "Y3Vyc29yX25leHRfMDFKNVE=",
 *         ending_before: "Y3Vyc29yX25leHRfMDFKNVE="
 *     }
 */
export interface ListAssetsRequest {
    /** Free-text search query (max 200 chars). */
    q?: string;
    /** Include a highlighted match snippet per hit (search mode only). */
    highlight?: boolean;
    /** Page size. Default 20, maximum 100. Out-of-range values are silently clamped; the response body's `limit` field reflects what was applied. */
    limit?: number;
    /** Opaque cursor — return the page starting strictly after this entity in the sort order. Mutually exclusive with `ending_before`. */
    starting_after?: string;
    /** Opaque cursor — return the page ending strictly before this entity in the sort order. Mutually exclusive with `starting_after`. */
    ending_before?: string;
}
