// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "00000000-0000-0000-0000-000000000000",
 *         name: "Truck 7B"
 *     }
 *
 * @example
 *     {
 *         id: "00000000-0000-0000-0000-000000000000",
 *         vin: "1HGCM82633A004352",
 *         plate_number: "AB-123-CD",
 *         make: "Volvo",
 *         model: "FH16",
 *         year: 2024
 *     }
 */
export interface UpdateAssetRequest {
    id: string;
    /** New display name. Omit to leave unchanged. */
    name?: string;
    /** New sub-kind. Omit to leave unchanged. */
    sub_kind?: string;
    /** New SAE J3016 autonomy level 0..5. Omit to leave unchanged. */
    autonomy_level?: number;
    /** New VIN: 17 chars of A-Z (no I, O, Q) and 0-9, uppercase. Unique per organization. Omit to leave unchanged. */
    vin?: string;
    /** New license plate. Omit to leave unchanged. */
    plate_number?: string;
    /** New manufacturer. Omit to leave unchanged. */
    make?: string;
    /** New model designation. Omit to leave unchanged. */
    model?: string;
    /** New model year: 1900 or later, no later than next year. Omit to leave unchanged. */
    year?: number;
}
