// This file was auto-generated by Fern from our API Definition.

import type * as NizamDashboard from "../index.js";

/**
 * Every artifact produced in one conversation, newest first.
 */
export interface ArtifactList {
    /** The conversation's artifacts, newest first. */
    artifacts: NizamDashboard.Artifact[];
    object: ArtifactList.Object_;
}

export namespace ArtifactList {
    export const Object_ = {
        ArtifactList: "artifact_list",
    } as const;
    export type Object_ = (typeof Object_)[keyof typeof Object_];
}
