// This file was auto-generated by Fern from our API Definition.

import type * as NizamDashboard from "../index.js";

/**
 * Every project the caller owns, newest first.
 */
export interface AssistantProjectList {
    /** The caller's projects, newest first. */
    projects: NizamDashboard.AssistantProject[];
    object: AssistantProjectList.Object_;
}

export namespace AssistantProjectList {
    export const Object_ = {
        AssistantProjectList: "assistant_project_list",
    } as const;
    export type Object_ = (typeof Object_)[keyof typeof Object_];
}
