// This file was auto-generated by Fern from our API Definition.

/**
 * ISO 3166-1 alpha-2 country with localized name + E.164 calling code.
 */
export interface Country {
    /** ISO 3166-1 alpha-2 code. */
    code?: string | undefined;
    /** Display name in the Accept-Language locale. */
    name?: string | undefined;
    /** E.164 country calling code with `+` prefix, or null if not allocated. */
    calling_code?: string | undefined;
    /** Object type discriminator (Stripe pattern). */
    object?: Country.Object_ | undefined;
}

export namespace Country {
    /** Object type discriminator (Stripe pattern). */
    export const Object_ = {
        Country: "country",
    } as const;
    export type Object_ = (typeof Object_)[keyof typeof Object_];
}
