// This file was auto-generated by Fern from our API Definition.

import type * as NizamDashboard from "../index.js";

/**
 * Create a new operator. The kind discriminator selects the variant.
 */
export type CreateOperatorRequest =
    | NizamDashboard.CreateOperatorRequest.Human
    | NizamDashboard.CreateOperatorRequest.Autonomous
    | NizamDashboard.CreateOperatorRequest.Teleoperated;

export namespace CreateOperatorRequest {
    export interface Human extends NizamDashboard.CreateHumanOperatorRequest {
        kind: "human";
    }

    export interface Autonomous extends NizamDashboard.CreateAutonomousOperatorRequest {
        kind: "autonomous";
    }

    export interface Teleoperated extends NizamDashboard.CreateTeleoperatedOperatorRequest {
        kind: "teleoperated";
    }
}
