// This file was auto-generated by Fern from our API Definition.

import type * as NizamDashboard from "../index.js";

/**
 * A buyable bundle of AI credits. Purchased credits do not expire, do not reset at a billing-period boundary, and are not forfeited on plan change, downgrade or cancellation.
 */
export interface CreditPack {
    /** Stable pack code — the handle a purchase names. */
    code: string;
    /** Display name. */
    name: string;
    /** Display copy. */
    description?: string | undefined;
    /** Credits granted on purchase. */
    credits: number;
    price: NizamDashboard.Money;
    /** Sort position on the purchase surface (ascending). */
    position: number;
    object: CreditPack.Object_;
}

export namespace CreditPack {
    export const Object_ = {
        CreditPack: "credit_pack",
    } as const;
    export type Object_ = (typeof Object_)[keyof typeof Object_];
}
