// This file was auto-generated by Fern from our API Definition.

import type * as NizamDashboard from "../index.js";

/**
 * A double-entry chart-of-accounts account and its current balance.
 */
export interface LedgerAccount {
    /** Unique identifier of the account. */
    id: string;
    /** Stable account code (the chart-of-accounts key). */
    code: string;
    /** Human-readable account name. */
    name: string;
    /** Accounting class. */
    account_type: LedgerAccount.AccountType;
    /** The side that increases the account. */
    normal_balance: LedgerAccount.NormalBalance;
    /** Lifecycle status. */
    status: LedgerAccount.Status;
    balance: NizamDashboard.Money;
    /** When the account was opened. */
    created_at: string;
    object: LedgerAccount.Object_;
}

export namespace LedgerAccount {
    /** Accounting class. */
    export const AccountType = {
        Asset: "asset",
        Liability: "liability",
        Equity: "equity",
        Revenue: "revenue",
        Expense: "expense",
    } as const;
    export type AccountType = (typeof AccountType)[keyof typeof AccountType];
    /** The side that increases the account. */
    export const NormalBalance = {
        Debit: "debit",
        Credit: "credit",
    } as const;
    export type NormalBalance = (typeof NormalBalance)[keyof typeof NormalBalance];
    /** Lifecycle status. */
    export const Status = {
        Active: "active",
        Archived: "archived",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
    export const Object_ = {
        LedgerAccount: "ledger_account",
    } as const;
    export type Object_ = (typeof Object_)[keyof typeof Object_];
}
