// This file was auto-generated by Fern from our API Definition.

import type * as NizamDashboard from "../index.js";

/**
 * What the hold preserves. The scope discriminator selects the variant.
 */
export type LegalHoldTarget = NizamDashboard.LegalHoldTarget.Subject | NizamDashboard.LegalHoldTarget.Conversation;

export namespace LegalHoldTarget {
    export interface Subject extends NizamDashboard.LegalHoldSubjectTarget {
        scope: "subject";
    }

    export interface Conversation extends NizamDashboard.LegalHoldConversationTarget {
        scope: "conversation";
    }
}
