// This file was auto-generated by Fern from our API Definition.

import type * as NizamDashboard from "../index.js";

/**
 * Envelope for paginated list responses (Stripe-style cursor pagination).
 */
export interface ListResponseCurrency {
    /** Object type discriminator (Stripe pattern). Always `list` for this envelope. */
    object?: ListResponseCurrency.Object_ | undefined;
    /** Page of resources. Empty array when there are no matches. */
    data?: NizamDashboard.Currency[] | undefined;
    /** True when more pages exist; pass `next_cursor` as `?starting_after=` to fetch the next page. */
    has_more?: boolean | undefined;
    /** Opaque cursor for the next page. `null` on the last page. */
    next_cursor?: string | undefined;
    /** Page size that produced this response. */
    limit?: number | undefined;
}

export namespace ListResponseCurrency {
    /** Object type discriminator (Stripe pattern). Always `list` for this envelope. */
    export const Object_ = {
        List: "list",
    } as const;
    export type Object_ = (typeof Object_)[keyof typeof Object_];
}
