// This file was auto-generated by Fern from our API Definition.

/**
 * Active total/unread for one category.
 */
export interface NotificationCategoryCount {
    /** Category. */
    category?: NotificationCategoryCount.Category | undefined;
    /** Active notifications in this category. */
    total?: number | undefined;
    /** Active unread notifications in this category. */
    unread?: number | undefined;
}

export namespace NotificationCategoryCount {
    /** Category. */
    export const Category = {
        Transactional: "transactional",
        Operational: "operational",
        Alert: "alert",
        Marketing: "marketing",
        Security: "security",
        System: "system",
    } as const;
    export type Category = (typeof Category)[keyof typeof Category];
}
