// This file was auto-generated by Fern from our API Definition.

/**
 * A claimed email domain and its verification state.
 */
export interface OrganizationDomain {
    /** Stable UUID of this domain claim. */
    id: string;
    /** The claimed domain, lowercase. */
    domain: string;
    /** Whether this is the organization's primary (display) domain. */
    is_primary: boolean;
    /** Whether ownership has been proven by the DNS TXT challenge. */
    verified: boolean;
    /** When ownership was proven, if it was. */
    verified_at?: string | undefined;
    /** DNS host to publish the record at. `@` means the domain apex (registrar convention). */
    txt_record_name: string;
    /** DNS record type to publish. */
    txt_record_type: string;
    /** Exact value of the TXT record to publish. */
    txt_record_value: string;
    /** When the last check-now ran, if ever. */
    last_checked_at?: string | undefined;
    /** Definitive outcome of the last check. `record_not_found` means the domain resolves but the TXT record is missing or wrong — publish it or wait for propagation; `domain_not_resolving` means the domain itself does not exist in DNS — check the spelling. */
    last_check_result?: OrganizationDomain.LastCheckResult | undefined;
    /** When the domain was claimed. */
    created_at: string;
    object: string;
}

export namespace OrganizationDomain {
    /** Definitive outcome of the last check. `record_not_found` means the domain resolves but the TXT record is missing or wrong — publish it or wait for propagation; `domain_not_resolving` means the domain itself does not exist in DNS — check the spelling. */
    export const LastCheckResult = {
        Verified: "verified",
        RecordNotFound: "record_not_found",
        DomainNotResolving: "domain_not_resolving",
    } as const;
    export type LastCheckResult = (typeof LastCheckResult)[keyof typeof LastCheckResult];
}
