// This file was auto-generated by Fern from our API Definition.

/**
 * Attempt a held or failed erasure again.
 */
export interface RetryErasureRequest {
    /** The organization the request belongs to. */
    organization_id: string;
}
