// This file was auto-generated by Fern from our API Definition.

import type * as NizamDashboard from "../index.js";

/**
 * Protocol configuration derived from the provider's published metadata.
 */
export type SsoConnectionConfiguration =
    | NizamDashboard.SsoConnectionConfiguration.Oidc
    | NizamDashboard.SsoConnectionConfiguration.Saml;

export namespace SsoConnectionConfiguration {
    export interface Oidc extends NizamDashboard.SsoOidcConfiguration {
        protocol: "oidc";
    }

    export interface Saml extends NizamDashboard.SsoSamlConfiguration {
        protocol: "saml";
    }
}
