// This file was auto-generated by Fern from our API Definition.

import type * as NizamDashboard from "../index.js";

/**
 * The organization's enterprise SSO connection.
 */
export interface SsoConnection {
    /** Stable UUID of the connection. */
    id: string;
    /** Federation protocol. */
    protocol: SsoConnection.Protocol;
    /** Lifecycle status. */
    status: SsoConnection.Status;
    /** Whether members must sign in through this connection (Nizam passwords refused). Only ever true while the connection is active. */
    enforce_sso: boolean;
    /** The break-glass admin exempt from enforcement, when enforcement is on. */
    break_glass_user_id?: string | undefined;
    /** Whether enforcement also covers members whose only role is operator (driver). Only ever true while enforcement is on. */
    applies_to_operators: boolean;
    /** Role granted when no asserted group matches a mapping. */
    fallback_role: SsoConnection.FallbackRole;
    /** Re-derive the member's role from asserted groups on every sign-in. Off by default: re-derivation silently reverts administrator role edits. */
    rederive_role_on_login: boolean;
    /** Directory-group → role rules, replaced wholesale on every configure — reconfigure forms must prefill them or they are deleted. */
    group_mappings: NizamDashboard.SsoGroupMapping[];
    configuration?: NizamDashboard.SsoConnectionConfiguration | undefined;
    setup: NizamDashboard.SsoSetupDetails;
    object: string;
}

export namespace SsoConnection {
    /** Federation protocol. */
    export const Protocol = {
        Oidc: "oidc",
        Saml: "saml",
    } as const;
    export type Protocol = (typeof Protocol)[keyof typeof Protocol];
    /** Lifecycle status. */
    export const Status = {
        Draft: "draft",
        Active: "active",
        Disabled: "disabled",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
    /** Role granted when no asserted group matches a mapping. */
    export const FallbackRole = {
        Admin: "admin",
        Dispatcher: "dispatcher",
        Manager: "manager",
        Staff: "staff",
        Viewer: "viewer",
        BillingAdmin: "billing_admin",
        Operator: "operator",
    } as const;
    export type FallbackRole = (typeof FallbackRole)[keyof typeof FallbackRole];
}
