// This file was auto-generated by Fern from our API Definition.

import type * as NizamDashboard from "../index.js";

/**
 * A subscription plan in the platform billing catalog (admin view).
 */
export interface SubscriptionPlan {
    /** Stable plan id. */
    id: string;
    /** Stable plan code (natural key). */
    code: string;
    /** Display name. */
    name: string;
    /** Description. */
    description?: string | undefined;
    /** Catalog lifecycle status. */
    status: SubscriptionPlan.Status;
    price: NizamDashboard.Money;
    setup_fee: NizamDashboard.Money;
    /** Pricing shape. */
    billing_model: SubscriptionPlan.BillingModel;
    /** Billing cadence. */
    billing_period: SubscriptionPlan.BillingPeriod;
    /** Sort position on the pricing page (ascending). */
    position: number;
    /** Default free-trial length in days. */
    default_trial_days?: number | undefined;
    features: NizamDashboard.PlanFeatures;
    /** Whether the plan is live (sellable to subscribers). */
    active: boolean;
    /** Whether the plan appears on the public pricing page. */
    visible: boolean;
    /** Processor (Stripe) Product id, once provisioned. */
    processor_product_id?: string | undefined;
    /** Processor (Stripe) Price id, once provisioned. */
    processor_price_id?: string | undefined;
    /** Lifecycle statuses this plan may legally transition to next. */
    allowed_transitions: SubscriptionPlan.AllowedTransitions.Item[];
    /** Creation time. */
    created_at: string;
    /** Last update time. */
    updated_at: string;
    object: SubscriptionPlan.Object_;
}

export namespace SubscriptionPlan {
    /** Catalog lifecycle status. */
    export const Status = {
        Draft: "draft",
        Active: "active",
        Grandfathered: "grandfathered",
        Retired: "retired",
        Archived: "archived",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
    /** Pricing shape. */
    export const BillingModel = {
        Free: "free",
        Flat: "flat",
        PerSeat: "per_seat",
        PerEvent: "per_event",
        Tiered: "tiered",
        Hybrid: "hybrid",
    } as const;
    export type BillingModel = (typeof BillingModel)[keyof typeof BillingModel];
    /** Billing cadence. */
    export const BillingPeriod = {
        Weekly: "weekly",
        Biweekly: "biweekly",
        Monthly: "monthly",
        Quarterly: "quarterly",
        Semiannual: "semiannual",
        Yearly: "yearly",
    } as const;
    export type BillingPeriod = (typeof BillingPeriod)[keyof typeof BillingPeriod];
    export type AllowedTransitions = AllowedTransitions.Item[];

    export namespace AllowedTransitions {
        /** Lifecycle statuses this plan may legally transition to next. */
        export const Item = {
            Draft: "draft",
            Active: "active",
            Grandfathered: "grandfathered",
            Retired: "retired",
            Archived: "archived",
        } as const;
        export type Item = (typeof Item)[keyof typeof Item];
    }

    export const Object_ = {
        SubscriptionPlan: "subscription_plan",
    } as const;
    export type Object_ = (typeof Object_)[keyof typeof Object_];
}
