// This file was auto-generated by Fern from our API Definition.

/**
 * The current authenticated user: identity + portal context + login activity.
 */
export interface User {
    /** Stable UUID. Equal to the Keycloak `sub` claim. */
    id: string;
    /** Which portal issued the bearer token used for this request. */
    portal: User.Portal;
    /** Keycloak Organization id the user belongs to. Null for cross-tenant platform admins. */
    organization_id?: string | undefined;
    roles: string[];
    /** The caller's effective permission ids for the active organization (epic #317): the union of catalog grants for every role they hold. Gate actions on these (`can("asset:create")`) rather than role strings, so frontend and backend reference the one catalog and cannot drift. Coarse and instance-independent; per-instance authority ('may delete THIS asset') is enforced server-side at the mutation, never precomputed here. */
    permissions: User.Permissions.Item[];
    /** Email shadowed from Keycloak. Null until the user completes a profile. */
    email?: string | undefined;
    /** Whether Keycloak has verified the user owns their email (OIDC `email_verified`). Read from the live token, not the shadow, an auth-time fact. Drives the profile UI's verified badge vs. the 'verify email' action. */
    email_verified: boolean;
    /** Display name. Seeded from Keycloak at first login; thereafter the user edits it via PATCH /v1/me (written through to Keycloak). */
    name?: string | undefined;
    /** Contact phone in E.164 format (app-managed via PATCH /v1/me). Null until the user sets one. Setting a phone stores an unverified contact number; it becomes a sign-in identifier only after a possession proof. */
    phone?: string | undefined;
    /** When the current phone was verified by a possession proof. Null while the phone is unverified contact data. Editing the phone clears it. */
    phone_verified_at?: string | undefined;
    /** Preferred UI language as a BCP 47 tag (app-managed via PATCH /v1/me). Null until the user sets one. */
    locale?: string | undefined;
    /** Preferred IANA timezone (app-managed via PATCH /v1/me). Null until the user sets one. */
    timezone?: string | undefined;
    /** Timestamp of this login. Null only on the very first call before provisioning completes. */
    last_login_at?: string | undefined;
    /** Total logins observed by this service. */
    login_count: number;
    /** File id of the current profile picture (epic #151 / #166); null until one is uploaded. Request bytes via the files download-url endpoint, or let `GET /users/{id}/profile-picture` pick the nearest thumbnail. */
    profile_picture_file_id?: string | undefined;
    /** Object type discriminator. */
    object: User.Object_;
}

export namespace User {
    /** Which portal issued the bearer token used for this request. */
    export const Portal = {
        Dashboard: "dashboard",
        Merchant: "merchant",
        Customer: "customer",
        Carrier: "carrier",
        Operator: "operator",
        PlatformStaff: "platform_staff",
        Admin: "admin",
    } as const;
    export type Portal = (typeof Portal)[keyof typeof Portal];
    export type Permissions = Permissions.Item[];

    export namespace Permissions {
        export const Item = {
            ActivityReadAll: "activity:read:all",
            AddonManage: "addon:manage",
            AddonRead: "addon:read",
            AiAgentProfileManage: "ai:agent_profile_manage",
            AiAgentProfileRead: "ai:agent_profile_read",
            ArtifactRead: "artifact:read",
            ArtifactSuggest: "artifact:suggest",
            ArtifactWrite: "artifact:write",
            AssetCreate: "asset:create",
            AssetDelete: "asset:delete",
            AssetDispose: "asset:dispose",
            AssetExport: "asset:export",
            AssetImport: "asset:import",
            AssetRead: "asset:read",
            AssetTransition: "asset:transition",
            AssetUpdate: "asset:update",
            AssignmentClose: "assignment:close",
            AssignmentCreate: "assignment:create",
            AssignmentRead: "assignment:read",
            AssistantDsarManage: "assistant_dsar:manage",
            AssistantErasureManage: "assistant_erasure:manage",
            AssistantInteractionReadAnalytics: "assistant_interaction:read_analytics",
            AssistantLegalHoldManage: "assistant_legal_hold:manage",
            AssistantSettingsManage: "assistant_settings:manage",
            AssistantSettingsRead: "assistant_settings:read",
            CodCollectionAdjust: "cod_collection:adjust",
            CodCollectionRead: "cod_collection:read",
            CodCollectionRecord: "cod_collection:record",
            CodCollectionSettle: "cod_collection:settle",
            CodCollectionWriteOff: "cod_collection:write_off",
            ConversationArchive: "conversation:archive",
            ConversationCreate: "conversation:create",
            ConversationDelete: "conversation:delete",
            ConversationExport: "conversation:export",
            ConversationRead: "conversation:read",
            ConversationShare: "conversation:share",
            ConversationUpdate: "conversation:update",
            CreditGrantManage: "credit_grant:manage",
            CreditNoteRead: "credit_note:read",
            FeedbackSubmit: "feedback:submit",
            InboundWebhookRead: "inbound-webhook:read",
            InviteCreate: "invite:create",
            InviteRead: "invite:read",
            InviteRevoke: "invite:revoke",
            InvoiceRead: "invoice:read",
            KeycloakProjectionAdminister: "keycloak-projection:administer",
            KnowledgeArchive: "knowledge:archive",
            KnowledgeCreate: "knowledge:create",
            KnowledgeDelete: "knowledge:delete",
            KnowledgeManageCollections: "knowledge:manage_collections",
            KnowledgePurge: "knowledge:purge",
            KnowledgeRead: "knowledge:read",
            KnowledgeReindex: "knowledge:reindex",
            KnowledgeUpdate: "knowledge:update",
            LedgerRead: "ledger:read",
            MemberRead: "member:read",
            MemberRemove: "member:remove",
            MemberResetPassword: "member:reset-password",
            MemberTransition: "member:transition",
            MerchantPayoutAdjust: "merchant_payout:adjust",
            MerchantPayoutBuild: "merchant_payout:build",
            MerchantPayoutRead: "merchant_payout:read",
            MerchantPayoutSettle: "merchant_payout:settle",
            MessageRead: "message:read",
            MessageSend: "message:send",
            MessageSwitchBranch: "message:switch_branch",
            NotificationDeliveryRead: "notification-delivery:read",
            OperatorCreate: "operator:create",
            OperatorCredential: "operator:credential",
            OperatorInvite: "operator:invite",
            OperatorRead: "operator:read",
            OperatorUpdate: "operator:update",
            OrgMaintenanceAdminister: "org-maintenance:administer",
            OrgAddonManage: "org_addon:manage",
            OrgAddonRead: "org_addon:read",
            PaymentRead: "payment:read",
            PlanManage: "plan:manage",
            PlanRead: "plan:read",
            ProjectManage: "project:manage",
            ServiceAccountAdminister: "service-account:administer",
            SsoManage: "sso:manage",
            SsoRead: "sso:read",
            SubscriptionManage: "subscription:manage",
            SubscriptionRead: "subscription:read",
            TaskCreate: "task:create",
            ToolCallDecide: "tool_call:decide",
            UserAdminister: "user:administer",
            UserInvite: "user:invite",
        } as const;
        export type Item = (typeof Item)[keyof typeof Item];
    }

    /** Object type discriminator. */
    export const Object_ = {
        User: "user",
    } as const;
    export type Object_ = (typeof Object_)[keyof typeof Object_];
}
