// This file was auto-generated by Fern from our API Definition.

/**
 * A persisted User row (admin-facing view).
 */
export interface UserResource {
    /** Stable UUID. */
    id?: string | undefined;
    /** Lifecycle status. */
    status?: UserResource.Status | undefined;
    /** Email shadowed from Keycloak. */
    email?: string | undefined;
    /** Display name. */
    name?: string | undefined;
    /** Timestamp of the last login. */
    last_login_at?: string | undefined;
    /** Total logins observed. */
    login_count?: number | undefined;
    /** Object type discriminator. */
    object?: UserResource.Object_ | undefined;
}

export namespace UserResource {
    /** Lifecycle status. */
    export const Status = {
        Active: "active",
        Suspended: "suspended",
        Deactivated: "deactivated",
        PendingVerification: "pending_verification",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
    /** Object type discriminator. */
    export const Object_ = {
        User: "user",
    } as const;
    export type Object_ = (typeof Object_)[keyof typeof Object_];
}
