// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         platform: "android",
 *         token: "fcm-Aa1Bb2Cc3\u2026"
 *     }
 */
export interface RegisterDevice {
    /** Push transport. */
    platform: RegisterDevice.Platform;
    /** The raw APNs/FCM/web-push token. Treated as a secret, never logged. */
    token: string;
}

export namespace RegisterDevice {
    /** Push transport. */
    export const Platform = {
        Ios: "ios",
        Android: "android",
        Web: "web",
    } as const;
    export type Platform = (typeof Platform)[keyof typeof Platform];
}
