// This file was auto-generated by Fern from our API Definition.

import type * as NizamDashboard from "../../../../index.js";

/**
 * @example
 *     {
 *         q: "<string>",
 *         starting_after: "Y3Vyc29yX25leHRfMDFKNVE=",
 *         ending_before: "Y3Vyc29yX25leHRfMDFKNVE="
 *     }
 */
export interface ListAllArtifactsRequest {
    /** Free-text title filter (max 200 chars). */
    q?: string;
    /** Filter by kind. Comma-separated; matched case-insensitively. */
    type?: NizamDashboard.ListAllArtifactsRequestTypeItem | NizamDashboard.ListAllArtifactsRequestTypeItem[];
    /** Narrow by whose conversation produced the artifact: `owned` (threads the caller owns) or `shared` (threads another member shared into the organization). Omit for both. */
    scope?: NizamDashboard.ListAllArtifactsRequestScope;
    /** Sort order. Allowed fields: `created_at`, `updated_at`, `title`. Append `:asc` or `:desc` to each field (direction required, e.g. `created_at:desc`), comma-separated for multi-sort; unknown fields or directions are rejected with `400 validation_failed`. */
    sort?: NizamDashboard.ListAllArtifactsRequestSortItem | NizamDashboard.ListAllArtifactsRequestSortItem[];
    /** Page size. Default 20, maximum 100. Out-of-range values are silently clamped; the response body's `limit` field reflects what was applied. */
    limit?: number;
    /** Opaque cursor: return the page starting strictly after this entity in the sort order. Mutually exclusive with `ending_before`. */
    starting_after?: string;
    /** Opaque cursor: return the page ending strictly before this entity in the sort order. Mutually exclusive with `starting_after`. */
    ending_before?: string;
}
