// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as NizamDashboard from "../../../index.js";

export declare namespace MerchantPayoutsClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * Settlement payments an organization disburses to its merchants.
 */
export class MerchantPayoutsClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<MerchantPayoutsClient.Options>;

    constructor(options: MerchantPayoutsClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * The caller's organization's merchant payouts, newest first. Keyset-paginated (`starting_after` / `ending_before`); no sort parameter. Org-scoped (RLS). Line items are on the detail read, not the list.
     *
     * @param {NizamDashboard.ListMerchantPayoutsRequest} request
     * @param {MerchantPayoutsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link NizamDashboard.UnauthorizedError}
     * @throws {@link NizamDashboard.ForbiddenError}
     * @throws {@link NizamDashboard.TooManyRequestsError}
     * @throws {@link NizamDashboard.InternalServerError}
     *
     * @example
     *     await client.merchantPayouts.listMerchantPayouts({
     *         starting_after: "Y3Vyc29yX25leHRfMDFKNVE=",
     *         ending_before: "Y3Vyc29yX25leHRfMDFKNVE="
     *     })
     */
    public listMerchantPayouts(
        request: NizamDashboard.ListMerchantPayoutsRequest = {},
        requestOptions?: MerchantPayoutsClient.RequestOptions,
    ): core.HttpResponsePromise<NizamDashboard.MerchantPayout> {
        return core.HttpResponsePromise.fromPromise(this.__listMerchantPayouts(request, requestOptions));
    }

    private async __listMerchantPayouts(
        request: NizamDashboard.ListMerchantPayoutsRequest = {},
        requestOptions?: MerchantPayoutsClient.RequestOptions,
    ): Promise<core.WithRawResponse<NizamDashboard.MerchantPayout>> {
        const { limit, starting_after: startingAfter, ending_before: endingBefore } = request;
        const _queryParams: Record<string, unknown> = {
            limit,
            starting_after: startingAfter,
            ending_before: endingBefore,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.NizamDashboardEnvironment.Production,
                "v1/merchant-payouts",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as NizamDashboard.MerchantPayout, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new NizamDashboard.UnauthorizedError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 403:
                    throw new NizamDashboard.ForbiddenError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 429:
                    throw new NizamDashboard.TooManyRequestsError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 500:
                    throw new NizamDashboard.InternalServerError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.NizamDashboardError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/v1/merchant-payouts");
    }

    /**
     * Builds a draft settlement statement for a merchant: pulls the merchant's reconcilable COD collections into source lines and reconciles them, appends any manual fee / adjustment lines, and foots gross/fees/net. 409 `merchant_payout.period_already_settled` if a live payout already covers the same merchant + period; 422 `merchant_payout.currency_mismatch` on a mixed-currency line.
     *
     * @param {NizamDashboard.BuildMerchantPayoutRequest} request
     * @param {MerchantPayoutsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link NizamDashboard.BadRequestError}
     * @throws {@link NizamDashboard.UnauthorizedError}
     * @throws {@link NizamDashboard.ForbiddenError}
     * @throws {@link NizamDashboard.ConflictError}
     * @throws {@link NizamDashboard.UnprocessableEntityError}
     * @throws {@link NizamDashboard.TooManyRequestsError}
     * @throws {@link NizamDashboard.InternalServerError}
     *
     * @example
     *     await client.merchantPayouts.buildMerchantPayout({
     *         "Idempotency-Key": "9f1e6d2a-7c3b-4e5f-8a91-0b2c3d4e5f60",
     *         merchant_id: "8f7e6d5c-4b3a-2918-0765-5e4d3c2b1a09",
     *         period_start: "2026-06-01T00:00:00Z",
     *         period_end: "2026-06-30T23:59:59Z",
     *         currency: "USD",
     *         payment_method: "wire",
     *         destination: {
     *             type: "bank_account",
     *             bank_name: "First National Bank",
     *             bank_account_name: "Acme Logistics LLC",
     *             account_last4: "6789",
     *             routing_last4: "0021",
     *             cheque_number: "001234"
     *         },
     *         lines: [{
     *                 line_type: "source"
     *             }],
     *         notes: "June COD settlement"
     *     })
     */
    public buildMerchantPayout(
        request: NizamDashboard.BuildMerchantPayoutRequest,
        requestOptions?: MerchantPayoutsClient.RequestOptions,
    ): core.HttpResponsePromise<NizamDashboard.MerchantPayout> {
        return core.HttpResponsePromise.fromPromise(this.__buildMerchantPayout(request, requestOptions));
    }

    private async __buildMerchantPayout(
        request: NizamDashboard.BuildMerchantPayoutRequest,
        requestOptions?: MerchantPayoutsClient.RequestOptions,
    ): Promise<core.WithRawResponse<NizamDashboard.MerchantPayout>> {
        const { "Idempotency-Key": idempotencyKey, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "Idempotency-Key": idempotencyKey }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.NizamDashboardEnvironment.Production,
                "v1/merchant-payouts",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as NizamDashboard.MerchantPayout, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new NizamDashboard.BadRequestError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 401:
                    throw new NizamDashboard.UnauthorizedError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 403:
                    throw new NizamDashboard.ForbiddenError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 409:
                    throw new NizamDashboard.ConflictError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 422:
                    throw new NizamDashboard.UnprocessableEntityError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 429:
                    throw new NizamDashboard.TooManyRequestsError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 500:
                    throw new NizamDashboard.InternalServerError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.NizamDashboardError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v1/merchant-payouts");
    }

    /**
     * Voids the payout before any money moves (`canceled`, terminal). Idempotent no-op if already canceled; an illegal edge → 409 `merchant_payout.invalid_transition`. No body.
     *
     * @param {NizamDashboard.CancelMerchantPayoutRequest} request
     * @param {MerchantPayoutsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link NizamDashboard.UnauthorizedError}
     * @throws {@link NizamDashboard.ForbiddenError}
     * @throws {@link NizamDashboard.NotFoundError}
     * @throws {@link NizamDashboard.ConflictError}
     * @throws {@link NizamDashboard.TooManyRequestsError}
     * @throws {@link NizamDashboard.InternalServerError}
     *
     * @example
     *     await client.merchantPayouts.cancelMerchantPayout({
     *         id: "00000000-0000-0000-0000-000000000000"
     *     })
     */
    public cancelMerchantPayout(
        request: NizamDashboard.CancelMerchantPayoutRequest,
        requestOptions?: MerchantPayoutsClient.RequestOptions,
    ): core.HttpResponsePromise<NizamDashboard.MerchantPayout> {
        return core.HttpResponsePromise.fromPromise(this.__cancelMerchantPayout(request, requestOptions));
    }

    private async __cancelMerchantPayout(
        request: NizamDashboard.CancelMerchantPayoutRequest,
        requestOptions?: MerchantPayoutsClient.RequestOptions,
    ): Promise<core.WithRawResponse<NizamDashboard.MerchantPayout>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.NizamDashboardEnvironment.Production,
                `v1/merchant-payouts/${core.url.encodePathParam(id)}/cancel`,
            ),
            method: "POST",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as NizamDashboard.MerchantPayout, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new NizamDashboard.UnauthorizedError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 403:
                    throw new NizamDashboard.ForbiddenError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 404:
                    throw new NizamDashboard.NotFoundError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 409:
                    throw new NizamDashboard.ConflictError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 429:
                    throw new NizamDashboard.TooManyRequestsError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 500:
                    throw new NizamDashboard.InternalServerError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.NizamDashboardError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/v1/merchant-payouts/{id}/cancel",
        );
    }

    /**
     * Records the payout as rejected / returned before settlement (`failed`) with an optional reason. Failed payouts are retryable. An illegal edge → 409 `merchant_payout.invalid_transition`.
     *
     * @param {NizamDashboard.FailMerchantPayoutRequest} request
     * @param {MerchantPayoutsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link NizamDashboard.UnauthorizedError}
     * @throws {@link NizamDashboard.ForbiddenError}
     * @throws {@link NizamDashboard.NotFoundError}
     * @throws {@link NizamDashboard.ConflictError}
     * @throws {@link NizamDashboard.TooManyRequestsError}
     * @throws {@link NizamDashboard.InternalServerError}
     *
     * @example
     *     await client.merchantPayouts.failMerchantPayout({
     *         id: "00000000-0000-0000-0000-000000000000",
     *         reason: "Bank rejected: account closed"
     *     })
     */
    public failMerchantPayout(
        request: NizamDashboard.FailMerchantPayoutRequest,
        requestOptions?: MerchantPayoutsClient.RequestOptions,
    ): core.HttpResponsePromise<NizamDashboard.MerchantPayout> {
        return core.HttpResponsePromise.fromPromise(this.__failMerchantPayout(request, requestOptions));
    }

    private async __failMerchantPayout(
        request: NizamDashboard.FailMerchantPayoutRequest,
        requestOptions?: MerchantPayoutsClient.RequestOptions,
    ): Promise<core.WithRawResponse<NizamDashboard.MerchantPayout>> {
        const { id, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.NizamDashboardEnvironment.Production,
                `v1/merchant-payouts/${core.url.encodePathParam(id)}/fail`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as NizamDashboard.MerchantPayout, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new NizamDashboard.UnauthorizedError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 403:
                    throw new NizamDashboard.ForbiddenError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 404:
                    throw new NizamDashboard.NotFoundError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 409:
                    throw new NizamDashboard.ConflictError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 429:
                    throw new NizamDashboard.TooManyRequestsError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 500:
                    throw new NizamDashboard.InternalServerError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.NizamDashboardError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/v1/merchant-payouts/{id}/fail",
        );
    }

    /**
     * Finalizes the draft statement and queues it for disbursement (`pending`). Idempotent no-op if already pending; an illegal edge → 409 `merchant_payout.invalid_transition`. No body.
     *
     * @param {NizamDashboard.FinalizeMerchantPayoutRequest} request
     * @param {MerchantPayoutsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link NizamDashboard.UnauthorizedError}
     * @throws {@link NizamDashboard.ForbiddenError}
     * @throws {@link NizamDashboard.NotFoundError}
     * @throws {@link NizamDashboard.ConflictError}
     * @throws {@link NizamDashboard.TooManyRequestsError}
     * @throws {@link NizamDashboard.InternalServerError}
     *
     * @example
     *     await client.merchantPayouts.finalizeMerchantPayout({
     *         id: "00000000-0000-0000-0000-000000000000"
     *     })
     */
    public finalizeMerchantPayout(
        request: NizamDashboard.FinalizeMerchantPayoutRequest,
        requestOptions?: MerchantPayoutsClient.RequestOptions,
    ): core.HttpResponsePromise<NizamDashboard.MerchantPayout> {
        return core.HttpResponsePromise.fromPromise(this.__finalizeMerchantPayout(request, requestOptions));
    }

    private async __finalizeMerchantPayout(
        request: NizamDashboard.FinalizeMerchantPayoutRequest,
        requestOptions?: MerchantPayoutsClient.RequestOptions,
    ): Promise<core.WithRawResponse<NizamDashboard.MerchantPayout>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.NizamDashboardEnvironment.Production,
                `v1/merchant-payouts/${core.url.encodePathParam(id)}/finalize`,
            ),
            method: "POST",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as NizamDashboard.MerchantPayout, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new NizamDashboard.UnauthorizedError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 403:
                    throw new NizamDashboard.ForbiddenError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 404:
                    throw new NizamDashboard.NotFoundError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 409:
                    throw new NizamDashboard.ConflictError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 429:
                    throw new NizamDashboard.TooManyRequestsError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 500:
                    throw new NizamDashboard.InternalServerError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.NizamDashboardError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/v1/merchant-payouts/{id}/finalize",
        );
    }

    /**
     * Parks the payout for compliance / dispute / banking-detail review (`on_hold`). Idempotent no-op if already on hold; an illegal edge → 409 `merchant_payout.invalid_transition`. No body.
     *
     * @param {NizamDashboard.HoldMerchantPayoutRequest} request
     * @param {MerchantPayoutsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link NizamDashboard.UnauthorizedError}
     * @throws {@link NizamDashboard.ForbiddenError}
     * @throws {@link NizamDashboard.NotFoundError}
     * @throws {@link NizamDashboard.ConflictError}
     * @throws {@link NizamDashboard.TooManyRequestsError}
     * @throws {@link NizamDashboard.InternalServerError}
     *
     * @example
     *     await client.merchantPayouts.holdMerchantPayout({
     *         id: "00000000-0000-0000-0000-000000000000"
     *     })
     */
    public holdMerchantPayout(
        request: NizamDashboard.HoldMerchantPayoutRequest,
        requestOptions?: MerchantPayoutsClient.RequestOptions,
    ): core.HttpResponsePromise<NizamDashboard.MerchantPayout> {
        return core.HttpResponsePromise.fromPromise(this.__holdMerchantPayout(request, requestOptions));
    }

    private async __holdMerchantPayout(
        request: NizamDashboard.HoldMerchantPayoutRequest,
        requestOptions?: MerchantPayoutsClient.RequestOptions,
    ): Promise<core.WithRawResponse<NizamDashboard.MerchantPayout>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.NizamDashboardEnvironment.Production,
                `v1/merchant-payouts/${core.url.encodePathParam(id)}/hold`,
            ),
            method: "POST",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as NizamDashboard.MerchantPayout, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new NizamDashboard.UnauthorizedError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 403:
                    throw new NizamDashboard.ForbiddenError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 404:
                    throw new NizamDashboard.NotFoundError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 409:
                    throw new NizamDashboard.ConflictError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 429:
                    throw new NizamDashboard.TooManyRequestsError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 500:
                    throw new NizamDashboard.InternalServerError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.NizamDashboardError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/v1/merchant-payouts/{id}/hold",
        );
    }

    /**
     * Submits the payout to the disbursement rail (`processing`). Idempotent no-op if already processing; an illegal edge → 409 `merchant_payout.invalid_transition`. No body.
     *
     * @param {NizamDashboard.ProcessMerchantPayoutRequest} request
     * @param {MerchantPayoutsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link NizamDashboard.UnauthorizedError}
     * @throws {@link NizamDashboard.ForbiddenError}
     * @throws {@link NizamDashboard.NotFoundError}
     * @throws {@link NizamDashboard.ConflictError}
     * @throws {@link NizamDashboard.TooManyRequestsError}
     * @throws {@link NizamDashboard.InternalServerError}
     *
     * @example
     *     await client.merchantPayouts.processMerchantPayout({
     *         id: "00000000-0000-0000-0000-000000000000"
     *     })
     */
    public processMerchantPayout(
        request: NizamDashboard.ProcessMerchantPayoutRequest,
        requestOptions?: MerchantPayoutsClient.RequestOptions,
    ): core.HttpResponsePromise<NizamDashboard.MerchantPayout> {
        return core.HttpResponsePromise.fromPromise(this.__processMerchantPayout(request, requestOptions));
    }

    private async __processMerchantPayout(
        request: NizamDashboard.ProcessMerchantPayoutRequest,
        requestOptions?: MerchantPayoutsClient.RequestOptions,
    ): Promise<core.WithRawResponse<NizamDashboard.MerchantPayout>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.NizamDashboardEnvironment.Production,
                `v1/merchant-payouts/${core.url.encodePathParam(id)}/process`,
            ),
            method: "POST",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as NizamDashboard.MerchantPayout, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new NizamDashboard.UnauthorizedError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 403:
                    throw new NizamDashboard.ForbiddenError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 404:
                    throw new NizamDashboard.NotFoundError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 409:
                    throw new NizamDashboard.ConflictError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 429:
                    throw new NizamDashboard.TooManyRequestsError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 500:
                    throw new NizamDashboard.InternalServerError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.NizamDashboardError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/v1/merchant-payouts/{id}/process",
        );
    }

    /**
     * Records a post-settlement clawback of a disbursed payout (`reversed`, terminal). An illegal edge → 409 `merchant_payout.invalid_transition`. No body.
     *
     * @param {NizamDashboard.ReverseMerchantPayoutRequest} request
     * @param {MerchantPayoutsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link NizamDashboard.UnauthorizedError}
     * @throws {@link NizamDashboard.ForbiddenError}
     * @throws {@link NizamDashboard.NotFoundError}
     * @throws {@link NizamDashboard.ConflictError}
     * @throws {@link NizamDashboard.TooManyRequestsError}
     * @throws {@link NizamDashboard.InternalServerError}
     *
     * @example
     *     await client.merchantPayouts.reverseMerchantPayout({
     *         id: "00000000-0000-0000-0000-000000000000"
     *     })
     */
    public reverseMerchantPayout(
        request: NizamDashboard.ReverseMerchantPayoutRequest,
        requestOptions?: MerchantPayoutsClient.RequestOptions,
    ): core.HttpResponsePromise<NizamDashboard.MerchantPayout> {
        return core.HttpResponsePromise.fromPromise(this.__reverseMerchantPayout(request, requestOptions));
    }

    private async __reverseMerchantPayout(
        request: NizamDashboard.ReverseMerchantPayoutRequest,
        requestOptions?: MerchantPayoutsClient.RequestOptions,
    ): Promise<core.WithRawResponse<NizamDashboard.MerchantPayout>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.NizamDashboardEnvironment.Production,
                `v1/merchant-payouts/${core.url.encodePathParam(id)}/reverse`,
            ),
            method: "POST",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as NizamDashboard.MerchantPayout, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new NizamDashboard.UnauthorizedError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 403:
                    throw new NizamDashboard.ForbiddenError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 404:
                    throw new NizamDashboard.NotFoundError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 409:
                    throw new NizamDashboard.ConflictError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 429:
                    throw new NizamDashboard.TooManyRequestsError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 500:
                    throw new NizamDashboard.InternalServerError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.NizamDashboardError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/v1/merchant-payouts/{id}/reverse",
        );
    }

    /**
     * Queues the payout for a future settlement run (`scheduled`) at the given time. An illegal edge → 409 `merchant_payout.invalid_transition`.
     *
     * @param {NizamDashboard.ScheduleMerchantPayoutRequest} request
     * @param {MerchantPayoutsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link NizamDashboard.UnauthorizedError}
     * @throws {@link NizamDashboard.ForbiddenError}
     * @throws {@link NizamDashboard.NotFoundError}
     * @throws {@link NizamDashboard.ConflictError}
     * @throws {@link NizamDashboard.UnprocessableEntityError}
     * @throws {@link NizamDashboard.TooManyRequestsError}
     * @throws {@link NizamDashboard.InternalServerError}
     *
     * @example
     *     await client.merchantPayouts.scheduleMerchantPayout({
     *         id: "00000000-0000-0000-0000-000000000000",
     *         scheduled_for: "2026-07-05T09:00:00Z"
     *     })
     */
    public scheduleMerchantPayout(
        request: NizamDashboard.ScheduleMerchantPayoutRequest,
        requestOptions?: MerchantPayoutsClient.RequestOptions,
    ): core.HttpResponsePromise<NizamDashboard.MerchantPayout> {
        return core.HttpResponsePromise.fromPromise(this.__scheduleMerchantPayout(request, requestOptions));
    }

    private async __scheduleMerchantPayout(
        request: NizamDashboard.ScheduleMerchantPayoutRequest,
        requestOptions?: MerchantPayoutsClient.RequestOptions,
    ): Promise<core.WithRawResponse<NizamDashboard.MerchantPayout>> {
        const { id, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.NizamDashboardEnvironment.Production,
                `v1/merchant-payouts/${core.url.encodePathParam(id)}/schedule`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as NizamDashboard.MerchantPayout, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new NizamDashboard.UnauthorizedError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 403:
                    throw new NizamDashboard.ForbiddenError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 404:
                    throw new NizamDashboard.NotFoundError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 409:
                    throw new NizamDashboard.ConflictError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 422:
                    throw new NizamDashboard.UnprocessableEntityError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 429:
                    throw new NizamDashboard.TooManyRequestsError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 500:
                    throw new NizamDashboard.InternalServerError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.NizamDashboardError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/v1/merchant-payouts/{id}/schedule",
        );
    }

    /**
     * Records the payout as disbursed (`sent`) with optional rail references. The processor-Connect rail is record-only — `processor_transfer_id` is stored with no transfer call. An illegal edge → 409 `merchant_payout.invalid_transition`.
     *
     * @param {NizamDashboard.MarkSentMerchantPayoutRequest} request
     * @param {MerchantPayoutsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link NizamDashboard.UnauthorizedError}
     * @throws {@link NizamDashboard.ForbiddenError}
     * @throws {@link NizamDashboard.NotFoundError}
     * @throws {@link NizamDashboard.ConflictError}
     * @throws {@link NizamDashboard.TooManyRequestsError}
     * @throws {@link NizamDashboard.InternalServerError}
     *
     * @example
     *     await client.merchantPayouts.sendMerchantPayout({
     *         id: "00000000-0000-0000-0000-000000000000",
     *         processor_transfer_id: "xfer_8f3a21bc9d",
     *         external_reference: "WIRE-2026-06-0042"
     *     })
     */
    public sendMerchantPayout(
        request: NizamDashboard.MarkSentMerchantPayoutRequest,
        requestOptions?: MerchantPayoutsClient.RequestOptions,
    ): core.HttpResponsePromise<NizamDashboard.MerchantPayout> {
        return core.HttpResponsePromise.fromPromise(this.__sendMerchantPayout(request, requestOptions));
    }

    private async __sendMerchantPayout(
        request: NizamDashboard.MarkSentMerchantPayoutRequest,
        requestOptions?: MerchantPayoutsClient.RequestOptions,
    ): Promise<core.WithRawResponse<NizamDashboard.MerchantPayout>> {
        const { id, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.NizamDashboardEnvironment.Production,
                `v1/merchant-payouts/${core.url.encodePathParam(id)}/send`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as NizamDashboard.MerchantPayout, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new NizamDashboard.UnauthorizedError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 403:
                    throw new NizamDashboard.ForbiddenError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 404:
                    throw new NizamDashboard.NotFoundError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 409:
                    throw new NizamDashboard.ConflictError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 429:
                    throw new NizamDashboard.TooManyRequestsError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 500:
                    throw new NizamDashboard.InternalServerError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.NizamDashboardError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/v1/merchant-payouts/{id}/send",
        );
    }

    /**
     * One merchant payout with its settlement lines. 404 when it does not exist in the caller's organization.
     *
     * @param {NizamDashboard.GetMerchantPayoutRequest} request
     * @param {MerchantPayoutsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link NizamDashboard.UnauthorizedError}
     * @throws {@link NizamDashboard.ForbiddenError}
     * @throws {@link NizamDashboard.NotFoundError}
     * @throws {@link NizamDashboard.TooManyRequestsError}
     * @throws {@link NizamDashboard.InternalServerError}
     *
     * @example
     *     await client.merchantPayouts.getMerchantPayout({
     *         merchantPayoutId: "00000000-0000-0000-0000-000000000000"
     *     })
     */
    public getMerchantPayout(
        request: NizamDashboard.GetMerchantPayoutRequest,
        requestOptions?: MerchantPayoutsClient.RequestOptions,
    ): core.HttpResponsePromise<NizamDashboard.MerchantPayout> {
        return core.HttpResponsePromise.fromPromise(this.__getMerchantPayout(request, requestOptions));
    }

    private async __getMerchantPayout(
        request: NizamDashboard.GetMerchantPayoutRequest,
        requestOptions?: MerchantPayoutsClient.RequestOptions,
    ): Promise<core.WithRawResponse<NizamDashboard.MerchantPayout>> {
        const { merchantPayoutId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.NizamDashboardEnvironment.Production,
                `v1/merchant-payouts/${core.url.encodePathParam(merchantPayoutId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as NizamDashboard.MerchantPayout, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new NizamDashboard.UnauthorizedError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 403:
                    throw new NizamDashboard.ForbiddenError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 404:
                    throw new NizamDashboard.NotFoundError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 429:
                    throw new NizamDashboard.TooManyRequestsError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                case 500:
                    throw new NizamDashboard.InternalServerError(
                        _response.error.body as NizamDashboard.ProblemDetail,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.NizamDashboardError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/v1/merchant-payouts/{merchantPayoutId}",
        );
    }
}
